/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import dao.MmlUsuariosDao;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author clari
 */
public class MmljDlgLogin extends javax.swing.JDialog {
    int contador = 3;
    /**
     * Creates new form MmljDlgLogin
     */
    public MmljDlgLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Login");
        getContentPane().setBackground(Color.WHITE);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mml_jLblSenha = new javax.swing.JLabel();
        mml_jLblUsuario = new javax.swing.JLabel();
        mml_jTxtUsuario = new javax.swing.JTextField();
        mml_jBtnConfirmar = new javax.swing.JButton();
        mml_jTxtSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mml_jLblSenha.setText("Senha");

        mml_jLblUsuario.setText("Usuário");

        mml_jTxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtUsuarioActionPerformed(evt);
            }
        });

        mml_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        mml_jBtnConfirmar.setText("Confirmar");
        mml_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnConfirmarActionPerformed(evt);
            }
        });

        mml_jTxtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mml_jTxtUsuario)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mml_jLblUsuario)
                            .addComponent(mml_jLblSenha))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(mml_jTxtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(144, 144, 144)
                    .addComponent(mml_jBtnConfirmar)
                    .addContainerGap(145, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(mml_jLblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mml_jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mml_jLblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mml_jTxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(134, 134, 134)
                    .addComponent(mml_jBtnConfirmar)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mml_jTxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtUsuarioActionPerformed

    private void mml_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        String valorUsuario = mml_jTxtUsuario.getText();
        String valorSenha = new String(mml_jTxtSenha.getPassword());

        MmlUsuariosDao usuarioDAO = new MmlUsuariosDao();

        boolean login = usuarioDAO.login(valorUsuario, valorSenha);
        if (login) {
            MmljFrmPrincipal JFrmPrincipal = new MmljFrmPrincipal();
            JFrmPrincipal.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "usuario ou senha incorretos");
            contador--;
            if (contador == 0) {
                JOptionPane.showMessageDialog(null, "3 tentativas falhas");
                System.exit(0);
            }
        }

    }//GEN-LAST:event_mml_jBtnConfirmarActionPerformed

    private void mml_jTxtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MmljDlgLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MmljDlgLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MmljDlgLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MmljDlgLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MmljDlgLogin dialog = new MmljDlgLogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mml_jBtnConfirmar;
    private javax.swing.JLabel mml_jLblSenha;
    private javax.swing.JLabel mml_jLblUsuario;
    private javax.swing.JPasswordField mml_jTxtSenha;
    private javax.swing.JTextField mml_jTxtUsuario;
    // End of variables declaration//GEN-END:variables
}
