/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Marlon
 */
public class MmljDlgVendasCarros extends javax.swing.JDialog {

       private boolean incluir;
    /**
     * Creates new form MmljDlgVendasProdutos
     */
    public MmljDlgVendasCarros(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Cadastro de Vendas de Carros");
        getContentPane().setBackground(Color.WHITE);
        habilitar(false);
    }
    
        public void habilitar(boolean value) {
        mml_jTxtIdVendasCarros.setEnabled(value);
        mml_jTxtIdVendas.setEnabled(value);
        mml_jTxtIdCarros.setEnabled(value);
        mml_jTxtTipo.setEnabled(value);
        mml_jTxtValorUnitario.setEnabled(value);

      
    }
        public void limpar() {
        mml_jTxtIdVendasCarros.setText("");
        mml_jTxtIdVendas.setText("");
        mml_jTxtIdCarros.setText("");
        mml_jTxtTipo.setText("");
        mml_jTxtValorUnitario.setText("");
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mml_jTxtIdCarros = new javax.swing.JTextField();
        mml_jLblValorUnitario = new javax.swing.JLabel();
        mml_jLblIdVendasCarros = new javax.swing.JLabel();
        mml_jTxtValorUnitario = new javax.swing.JTextField();
        mml_jTxtIdVendasCarros = new javax.swing.JTextField();
        mml_jLblIdVenda = new javax.swing.JLabel();
        mml_jTxtIdVendas = new javax.swing.JTextField();
        mml_jLblTipo = new javax.swing.JLabel();
        mml_jLblIdCarros = new javax.swing.JLabel();
        mml_jTxtTipo = new javax.swing.JTextField();
        jBtnOK = new javax.swing.JToggleButton();
        jBtnCancelar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mml_jTxtIdCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtIdCarrosActionPerformed(evt);
            }
        });

        mml_jLblValorUnitario.setText("Valor Unitario");

        mml_jLblIdVendasCarros.setText("Id Vendas_Carros");

        mml_jTxtValorUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtValorUnitarioActionPerformed(evt);
            }
        });

        mml_jTxtIdVendasCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtIdVendasCarrosActionPerformed(evt);
            }
        });

        mml_jLblIdVenda.setText("Id Venda");

        mml_jTxtIdVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtIdVendasActionPerformed(evt);
            }
        });

        mml_jLblTipo.setText("Tipo");

        mml_jLblIdCarros.setText("Id Carros");

        mml_jTxtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtTipoActionPerformed(evt);
            }
        });

        jBtnOK.setText("OK");
        jBtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOKActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(mml_jTxtTipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addComponent(mml_jTxtIdVendasCarros, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mml_jLblIdVendasCarros, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(mml_jLblTipo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mml_jTxtIdVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mml_jLblIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mml_jLblIdCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mml_jTxtIdCarros, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mml_jLblValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mml_jTxtValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jBtnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblIdCarros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtIdCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblIdVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtIdVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblIdVendasCarros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtIdVendasCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblValorUnitario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mml_jTxtIdCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtIdCarrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtIdCarrosActionPerformed

    private void mml_jTxtValorUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtValorUnitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtValorUnitarioActionPerformed

    private void mml_jTxtIdVendasCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtIdVendasCarrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtIdVendasCarrosActionPerformed

    private void mml_jTxtIdVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtIdVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtIdVendasActionPerformed

    private void mml_jTxtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtTipoActionPerformed

    private void jBtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOKActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jBtnOKActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendasCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendasCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendasCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendasCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MmljDlgVendasCarros dialog = new MmljDlgVendasCarros(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jBtnCancelar;
    private javax.swing.JToggleButton jBtnOK;
    private javax.swing.JLabel mml_jLblIdCarros;
    private javax.swing.JLabel mml_jLblIdVenda;
    private javax.swing.JLabel mml_jLblIdVendasCarros;
    private javax.swing.JLabel mml_jLblTipo;
    private javax.swing.JLabel mml_jLblValorUnitario;
    private javax.swing.JTextField mml_jTxtIdCarros;
    private javax.swing.JTextField mml_jTxtIdVendas;
    private javax.swing.JTextField mml_jTxtIdVendasCarros;
    private javax.swing.JTextField mml_jTxtTipo;
    private javax.swing.JTextField mml_jTxtValorUnitario;
    // End of variables declaration//GEN-END:variables
}
