/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;


import bean.MmlCarros;
import dao.MmlCarrosDao;

import tools.Util;

/**
 *
 * @author Marlon
 */
public class MmljDlgCarros extends javax.swing.JDialog {
    
    private boolean incluir;

   
    public MmljDlgCarros(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Cadastro de Carros");
       Util.habilitar(false,mml_JTxtPrecoVenda, mml_jTxtModelo,  mml_jTxtCor, mml_jTxtAno, mml_jTxtPreco, mml_jTxtMarca, mml_jTxtCodigo,mml_jBtnConfirmar, mml_jBtnCancelar,mml_jBtnPesquisar, mml_jBtnExcluir,mml_jBtnAlterar);
        
    }
      public MmlCarros viewBean() {
        MmlCarros mmlCarros = new MmlCarros();
        int codigo = Util.strToInt(mml_jTxtCodigo.getText());
        mmlCarros.setMmlIdCarros(codigo);
        mmlCarros.setMmlPrecoVenda(Util.strToDouble(mml_JTxtPrecoVenda.getText()));
        mmlCarros.setMmlModelo(mml_jTxtModelo.getText());
        mmlCarros.setMmlMarca(mml_jTxtMarca.getText());
        mmlCarros.setMmlCor(mml_jTxtCor.getText());
        mmlCarros.setMmlAno(Util.strToDate(mml_jTxtAno.getText()));
        mmlCarros.setMmlPreco(Util.strToDouble(mml_jTxtPreco.getText()));
        return mmlCarros;
    }

    public void beanView(MmlCarros mmlCarros) {
        mml_jTxtCodigo.setText(Util.intToStr(mmlCarros.getMmlIdCarros()));
        mml_JTxtPrecoVenda.setText(Util.doubleToStr(mmlCarros.getMmlPrecoVenda()));
        mml_jTxtModelo.setText(mmlCarros.getMmlModelo());
        mml_jTxtMarca.setText(mmlCarros.getMmlMarca());
        mml_jTxtCor.setText(mmlCarros.getMmlCor());
        mml_jTxtAno.setText(Util.dateToStr(mmlCarros.getMmlAno()));
        mml_jTxtPreco.setText(Util.doubleToStr(mmlCarros.getMmlPreco()));
    }
    
      

      

    public void limpar(){
    mml_jTxtCodigo.setText("");
    mml_jTxtModelo.setText("");
    mml_jTxtMarca.setText("");
    mml_jTxtCor.setText("");
    mml_jTxtAno.setText("");
    mml_jTxtPreco.setText("");
    mml_JTxtPrecoVenda.setText("");
}
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mml_JLblPrecoVenda = new javax.swing.JLabel();
        mml_JTxtPrecoVenda = new javax.swing.JTextField();
        mml_JLblCodigo = new javax.swing.JLabel();
        mml_jTxtCodigo = new javax.swing.JTextField();
        mml_jLblModelo = new javax.swing.JLabel();
        mml_jTxtModelo = new javax.swing.JTextField();
        mml_jLblMarca = new javax.swing.JLabel();
        mml_jTxtMarca = new javax.swing.JTextField();
        mml_jLblCor = new javax.swing.JLabel();
        mml_jTxtCor = new javax.swing.JTextField();
        mml_jLblAno = new javax.swing.JLabel();
        mml_jTxtAno = new javax.swing.JTextField();
        mml_jLblPreco = new javax.swing.JLabel();
        mml_jTxtPreco = new javax.swing.JTextField();
        mml_jBtnCancelar = new javax.swing.JButton();
        mml_jBtnPesquisar = new javax.swing.JButton();
        mml_jBtnIncluir = new javax.swing.JButton();
        mml_jBtnAlterar = new javax.swing.JButton();
        mml_jBtnExcluir = new javax.swing.JButton();
        mml_jBtnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mml_JLblPrecoVenda.setText("Preço Venda");

        mml_JTxtPrecoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_JTxtPrecoVendaActionPerformed(evt);
            }
        });

        mml_JLblCodigo.setText("Código");

        mml_jTxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtCodigoActionPerformed(evt);
            }
        });

        mml_jLblModelo.setText("Modelo");

        mml_jLblMarca.setText("Marca");

        mml_jLblCor.setText("Cor");

        mml_jLblAno.setText("Ano");

        mml_jLblPreco.setText("Preço");

        mml_jTxtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtPrecoActionPerformed(evt);
            }
        });

        mml_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        mml_jBtnCancelar.setText("Cancelar");
        mml_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnCancelarActionPerformed(evt);
            }
        });

        mml_jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar (2)_1.png"))); // NOI18N
        mml_jBtnPesquisar.setText("Pesquisar");
        mml_jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnPesquisarActionPerformed(evt);
            }
        });

        mml_jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        mml_jBtnIncluir.setText("Incluir");
        mml_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnIncluirActionPerformed(evt);
            }
        });

        mml_jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        mml_jBtnAlterar.setText("Alterar");
        mml_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnAlterarActionPerformed(evt);
            }
        });

        mml_jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        mml_jBtnExcluir.setText("Excluir");
        mml_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnExcluirActionPerformed(evt);
            }
        });

        mml_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        mml_jBtnConfirmar.setText("Confirmar");
        mml_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mml_JTxtPrecoVenda)
                            .addComponent(mml_jTxtModelo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mml_jLblModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mml_JLblPrecoVenda))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mml_JLblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mml_jTxtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(mml_jLblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mml_jTxtMarca)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mml_jTxtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mml_jLblCor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mml_jLblAno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mml_jTxtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mml_jLblPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mml_jTxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mml_jBtnIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mml_jBtnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mml_jBtnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mml_jBtnConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mml_jBtnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mml_jBtnPesquisar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblAno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mml_JLblPrecoVenda)
                            .addComponent(mml_JLblCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mml_JTxtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mml_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mml_jLblModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mml_jTxtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mml_jLblMarca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mml_jTxtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mml_jLblCor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mml_jTxtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mml_jLblPreco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mml_jTxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mml_jBtnIncluir)
                    .addComponent(mml_jBtnAlterar)
                    .addComponent(mml_jBtnExcluir)
                    .addComponent(mml_jBtnConfirmar)
                    .addComponent(mml_jBtnCancelar)
                    .addComponent(mml_jBtnPesquisar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mml_jTxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtCodigoActionPerformed

    private void mml_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnExcluirActionPerformed
        // TODO add your handling code here:
      if (Util.perguntar("Excluir?") == true) {
        MmlCarrosDao mmlCarrosDao = new MmlCarrosDao();
        mmlCarrosDao.delete(viewBean()); 
        Util.habilitar(true, mml_jBtnAlterar, mml_jBtnCancelar, mml_jBtnExcluir);
        Util.habilitar(false,  mml_jBtnIncluir, mml_jBtnPesquisar,mml_jBtnAlterar, mml_jBtnExcluir);
        Util.limpar(mml_JLblPrecoVenda, mml_jLblModelo ,mml_JLblCodigo , mml_jLblMarca, mml_jLblCor, mml_jLblAno, mml_jLblPreco);
    }
 
    }//GEN-LAST:event_mml_jBtnExcluirActionPerformed

    private void mml_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnIncluirActionPerformed
        incluir = true;
        Util.habilitar(true, mml_JTxtPrecoVenda, mml_jTxtModelo, mml_jTxtCor, mml_jTxtAno, mml_jTxtPreco, mml_jTxtCodigo, mml_jTxtMarca, mml_jBtnConfirmar, mml_jBtnCancelar);
        Util.habilitar(false, mml_jBtnIncluir, mml_jBtnPesquisar);
        Util.limpar(mml_JLblPrecoVenda, mml_jLblModelo, mml_JLblCodigo, mml_jLblMarca, mml_jLblCor, mml_jLblAno, mml_jLblPreco);
        mml_JTxtPrecoVenda.grabFocus();
    }//GEN-LAST:event_mml_jBtnIncluirActionPerformed

    private void mml_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
       MmlCarrosDao mmlCarrosDao = new MmlCarrosDao();
        if (incluir) {
            mmlCarrosDao.insert(viewBean());
        } else {
            mmlCarrosDao.update(viewBean());
        }
        Util.habilitar(true, mml_JLblPrecoVenda, mml_jLblModelo, mml_JLblCodigo, mml_jLblMarca, mml_jLblCor, mml_jLblAno, mml_jLblPreco, mml_jBtnConfirmar, mml_jBtnCancelar);
        Util.habilitar(false, mml_jBtnIncluir, mml_jBtnPesquisar);
        Util.limpar(mml_JLblPrecoVenda, mml_jLblModelo, mml_JLblCodigo, mml_jLblMarca, mml_jLblCor, mml_jLblAno, mml_jLblPreco);
    }//GEN-LAST:event_mml_jBtnConfirmarActionPerformed

    private void mml_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, mml_JLblPrecoVenda, mml_jLblModelo, mml_JLblCodigo, mml_jLblMarca, mml_jLblCor, mml_jLblAno, mml_jLblPreco, mml_jBtnConfirmar, mml_jBtnCancelar, mml_jBtnAlterar, mml_jBtnExcluir);
        Util.habilitar(true,  mml_jBtnIncluir, mml_jBtnPesquisar);
        Util.limpar(mml_JLblPrecoVenda, mml_jLblModelo, mml_JLblCodigo, mml_jLblMarca, mml_jLblCor, mml_jLblAno, mml_jLblPreco);
    }//GEN-LAST:event_mml_jBtnCancelarActionPerformed

    private void mml_jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
           // TODO add your handling code here:
        Mml_jDlgCarrosPesquisar  mml_jDlgCarrosPesquisar = new  Mml_jDlgCarrosPesquisar(null, true);
        mml_jDlgCarrosPesquisar.setTelaPai(this);
        mml_jDlgCarrosPesquisar.setVisible(true);
       

    }//GEN-LAST:event_mml_jBtnPesquisarActionPerformed

    private void mml_JTxtPrecoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_JTxtPrecoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_JTxtPrecoVendaActionPerformed

    private void mml_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        incluir = false;
        Util.habilitar(true, mml_JLblPrecoVenda, mml_jLblModelo, mml_JLblCodigo, mml_jLblMarca, mml_jLblCor, mml_jLblAno, mml_jLblPreco,mml_jBtnConfirmar, mml_jBtnCancelar);
        Util.habilitar(false, mml_jBtnIncluir, mml_jBtnIncluir, mml_jBtnAlterar);
        mml_JLblPrecoVenda.grabFocus();
    }//GEN-LAST:event_mml_jBtnAlterarActionPerformed

    private void mml_jTxtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtPrecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MmljDlgCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MmljDlgCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MmljDlgCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MmljDlgCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MmljDlgCarros dialog = new MmljDlgCarros(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel mml_JLblCodigo;
    private javax.swing.JLabel mml_JLblPrecoVenda;
    private javax.swing.JTextField mml_JTxtPrecoVenda;
    private javax.swing.JButton mml_jBtnAlterar;
    private javax.swing.JButton mml_jBtnCancelar;
    private javax.swing.JButton mml_jBtnConfirmar;
    private javax.swing.JButton mml_jBtnExcluir;
    private javax.swing.JButton mml_jBtnIncluir;
    private javax.swing.JButton mml_jBtnPesquisar;
    private javax.swing.JLabel mml_jLblAno;
    private javax.swing.JLabel mml_jLblCor;
    private javax.swing.JLabel mml_jLblMarca;
    private javax.swing.JLabel mml_jLblModelo;
    private javax.swing.JLabel mml_jLblPreco;
    private javax.swing.JTextField mml_jTxtAno;
    private javax.swing.JTextField mml_jTxtCodigo;
    private javax.swing.JTextField mml_jTxtCor;
    private javax.swing.JTextField mml_jTxtMarca;
    private javax.swing.JTextField mml_jTxtModelo;
    private javax.swing.JTextField mml_jTxtPreco;
    // End of variables declaration//GEN-END:variables
}
