/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;


import bean.MmlVendedor;
import dao.MmlClienteDao;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import tools.Util;

/**
 *
 * @author Marlon
 */
public class MmljDlgVendedor extends javax.swing.JDialog {

     private boolean incluir;
    /**
     * Creates new form jDlgVendedor
     */
    public MmljDlgVendedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
       
        setLocationRelativeTo(null);
        setTitle("Cadastro de Vendedor");
        getContentPane().setBackground(Color.WHITE);
        
    }
    public MmlVendedor viewBean() {
    MmlVendedor mmlVendedor = new MmlVendedor();
    int codigo = Util.strToInt(mml_jTxtCodigo.getText());
    mmlVendedor.setMmlIdVendedor(codigo);
    mmlVendedor.setMmlNome(mml_jTxtNome.getText());
    mmlVendedor.setMmlCredencial(Util.strToInt(mml_jTxtCredencial.getText()));
    mmlVendedor.setMmlExpediente(mml_jTxtExpediente.getText());
    mmlVendedor.setMmlCpf(mml_jTxtCpf.getText());
    mmlVendedor.setMmlAtivo(mml_jCBocAtivo.isSelected() ? "S" : "N");
    mmlVendedor.setMmlDataNascimente(Util.strToDate(mml_jTxtDataNasc.getText()));
    return mmlVendedor;
}

public void beanView(MmlVendedor mmlVendedor) {
    mml_jTxtCodigo.setText(Util.intToStr(mmlVendedor.getMmlIdVendedor()));
    mml_jTxtNome.setText(mmlVendedor.getMmlNome());
    mml_jTxtCredencial.setText(Util.intToStr(mmlVendedor.getMmlCredencial()));
    mml_jTxtExpediente.setText(mmlVendedor.getMmlExpediente());
    mml_jTxtCpf.setText(mmlVendedor.getMmlCpf());
    mml_jCBocAtivo.setSelected("S".equals(mmlVendedor.getMmlAtivo()));
    mml_jTxtDataNasc.setText(Util.dateToStr(mmlVendedor.getMmlDataNascimente()));
}


    

   

    
        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mml_jLblNome = new javax.swing.JLabel();
        mml_jTxtNome = new javax.swing.JTextField();
        mml_jLblCodigo = new javax.swing.JLabel();
        mml_jTxtCodigo = new javax.swing.JTextField();
        mml_jLblCredencial = new javax.swing.JLabel();
        mml_jTxtCredencial = new javax.swing.JTextField();
        mml_jLblExpediente = new javax.swing.JLabel();
        mml_jTxtExpediente = new javax.swing.JTextField();
        mml_jLblCpf = new javax.swing.JLabel();
        mml_jTxtCpf = new javax.swing.JTextField();
        mml_jLblDataNasc = new javax.swing.JLabel();
        mml_jTxtDataNasc = new javax.swing.JTextField();
        mml_jLblAtivo = new javax.swing.JLabel();
        mml_jCBocAtivo = new javax.swing.JCheckBox();
        mml_jBtnPesquisar = new javax.swing.JButton();
        mml_jBtnIncluir = new javax.swing.JButton();
        mml_jBtnAlterar = new javax.swing.JButton();
        mml_jBtnExcluir = new javax.swing.JButton();
        mml_jBtnConfirmar = new javax.swing.JButton();
        mml_jBtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mml_jLblNome.setText("Nome");

        mml_jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtNomeActionPerformed(evt);
            }
        });

        mml_jLblCodigo.setText("Código");

        mml_jTxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtCodigoActionPerformed(evt);
            }
        });

        mml_jLblCredencial.setText("Credencial");

        mml_jTxtCredencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtCredencialActionPerformed(evt);
            }
        });

        mml_jLblExpediente.setText("Expediente");

        mml_jTxtExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtExpedienteActionPerformed(evt);
            }
        });

        mml_jLblCpf.setText("CPF");

        mml_jTxtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtCpfActionPerformed(evt);
            }
        });

        mml_jLblDataNasc.setText("Data de Nascimento");

        mml_jTxtDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtDataNascActionPerformed(evt);
            }
        });

        mml_jLblAtivo.setText("Ativo");

        mml_jCBocAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jCBocAtivoActionPerformed(evt);
            }
        });

        mml_jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar (2)_1.png"))); // NOI18N
        mml_jBtnPesquisar.setText("Pesquisar");
        mml_jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnPesquisarActionPerformed(evt);
            }
        });

        mml_jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        mml_jBtnIncluir.setText("Incluir");
        mml_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnIncluirActionPerformed(evt);
            }
        });

        mml_jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        mml_jBtnAlterar.setText("Alterar");
        mml_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnAlterarActionPerformed(evt);
            }
        });

        mml_jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        mml_jBtnExcluir.setText("Excluir");
        mml_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnExcluirActionPerformed(evt);
            }
        });

        mml_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        mml_jBtnConfirmar.setText("Confirmar");
        mml_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnConfirmarActionPerformed(evt);
            }
        });

        mml_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        mml_jBtnCancelar.setText("Cancelar");
        mml_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(mml_jTxtExpediente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(mml_jLblNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mml_jTxtNome, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(mml_jLblExpediente))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mml_jTxtCpf)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mml_jLblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mml_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mml_jLblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mml_jLblCredencial, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mml_jTxtCredencial)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(mml_jLblAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mml_jTxtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(mml_jCBocAtivo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mml_jBtnIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mml_jBtnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mml_jBtnExcluir)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(mml_jBtnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jBtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jBtnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblCredencial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtCredencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblExpediente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mml_jLblDataNasc)
                    .addComponent(mml_jLblAtivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mml_jTxtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mml_jCBocAtivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mml_jBtnIncluir)
                    .addComponent(mml_jBtnAlterar)
                    .addComponent(mml_jBtnExcluir)
                    .addComponent(mml_jBtnConfirmar)
                    .addComponent(mml_jBtnCancelar)
                    .addComponent(mml_jBtnPesquisar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mml_jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtNomeActionPerformed

    private void mml_jTxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtCodigoActionPerformed

    private void mml_jTxtCredencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtCredencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtCredencialActionPerformed

    private void mml_jTxtExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtExpedienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtExpedienteActionPerformed

    private void mml_jTxtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtCpfActionPerformed

    private void mml_jTxtDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtDataNascActionPerformed

    private void mml_jCBocAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jCBocAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jCBocAtivoActionPerformed

    private void mml_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnExcluirActionPerformed
        // TODO add your handling code here:
         if (Util.perguntar("Excluir?") == true) {
            MmlClienteDao mmlClienteDao = new MmlClienteDao();
            mmlClienteDao.delete(viewBean());
            Util.habilitar(false, mml_jBtnAlterar, mml_jBtnCancelar, mml_jBtnExcluir);
            Util.habilitar(true, mml_jBtnIncluir, mml_jBtnPesquisar);
            Util.limpar( mml_jTxtNome, mml_jTxtExpediente,mml_jTxtDataNasc,mml_jCBocAtivo, mml_jTxtCpf,mml_jTxtCodigo,mml_jTxtCredencial);
        }
           
        
            
        
    }//GEN-LAST:event_mml_jBtnExcluirActionPerformed

    private void mml_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        incluir = true;
        Util.habilitar(true, mml_jTxtNome, mml_jTxtExpediente,mml_jTxtDataNasc,mml_jCBocAtivo, mml_jTxtCpf,mml_jTxtCodigo,mml_jTxtCredencial, mml_jBtnConfirmar, mml_jBtnCancelar);
        Util.habilitar(false, mml_jBtnIncluir, mml_jBtnPesquisar);
        Util.limpar(mml_jTxtNome, mml_jTxtExpediente,mml_jTxtDataNasc,mml_jCBocAtivo, mml_jTxtCpf,mml_jTxtCodigo,mml_jTxtCredencial);
        mml_jTxtNome.grabFocus();
        
    }//GEN-LAST:event_mml_jBtnIncluirActionPerformed

    private void mml_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
         MmlClienteDao mmlClienteDao = new MmlClienteDao();
        if (incluir) {
            mmlClienteDao.insert(viewBean());
        } else {
            mmlClienteDao.update(viewBean());
        }
        Util.habilitar(false,mml_jTxtNome, mml_jTxtExpediente,mml_jTxtDataNasc,mml_jCBocAtivo, mml_jTxtCpf,mml_jTxtCodigo,mml_jTxtCredencial, mml_jBtnConfirmar, mml_jBtnCancelar);
        Util.habilitar(true,  mml_jBtnIncluir, mml_jBtnPesquisar);
        Util.limpar(mml_jTxtNome, mml_jTxtExpediente,mml_jTxtDataNasc,mml_jCBocAtivo, mml_jTxtCpf,mml_jTxtCodigo,mml_jTxtCredencial);
    }//GEN-LAST:event_mml_jBtnConfirmarActionPerformed

    private void mml_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnCancelarActionPerformed
        // TODO add your handling code here:
     
        Util.habilitar(false, mml_jTxtNome, mml_jTxtExpediente,mml_jTxtDataNasc,mml_jCBocAtivo, mml_jTxtCpf,mml_jTxtCodigo,mml_jTxtCredencial, mml_jBtnConfirmar, mml_jBtnCancelar, mml_jBtnAlterar, mml_jBtnExcluir);
        Util.habilitar(true,  mml_jBtnIncluir, mml_jBtnPesquisar);
        Util.limpar(mml_jTxtNome, mml_jTxtExpediente,mml_jTxtDataNasc,mml_jCBocAtivo, mml_jTxtCpf,mml_jTxtCodigo,mml_jTxtCredencial);
    }//GEN-LAST:event_mml_jBtnCancelarActionPerformed

    private void mml_jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnPesquisarActionPerformed
      Mml_jDlgVendedorPesquisar mml_jDlgVendedorPesquisar = new Mml_jDlgVendedorPesquisar(null, true);
        mml_jDlgVendedorPesquisar.setTelaPai(this);
        mml_jDlgVendedorPesquisar.setVisible(true);
       

    }//GEN-LAST:event_mml_jBtnPesquisarActionPerformed

    private void mml_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnAlterarActionPerformed
        // TODO add your handling code here:
     incluir = false;
        Util.habilitar(true,mml_jTxtNome, mml_jTxtExpediente,mml_jTxtDataNasc,mml_jCBocAtivo, mml_jTxtCpf,mml_jTxtCodigo,mml_jTxtCredencial, mml_jBtnConfirmar, mml_jBtnCancelar);
        Util.habilitar(false, mml_jBtnExcluir, mml_jBtnIncluir, mml_jBtnAlterar);
        mml_jTxtNome.grabFocus();
        
    }//GEN-LAST:event_mml_jBtnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MmljDlgVendedor dialog = new MmljDlgVendedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mml_jBtnAlterar;
    private javax.swing.JButton mml_jBtnCancelar;
    private javax.swing.JButton mml_jBtnConfirmar;
    private javax.swing.JButton mml_jBtnExcluir;
    private javax.swing.JButton mml_jBtnIncluir;
    private javax.swing.JButton mml_jBtnPesquisar;
    private javax.swing.JCheckBox mml_jCBocAtivo;
    private javax.swing.JLabel mml_jLblAtivo;
    private javax.swing.JLabel mml_jLblCodigo;
    private javax.swing.JLabel mml_jLblCpf;
    private javax.swing.JLabel mml_jLblCredencial;
    private javax.swing.JLabel mml_jLblDataNasc;
    private javax.swing.JLabel mml_jLblExpediente;
    private javax.swing.JLabel mml_jLblNome;
    private javax.swing.JTextField mml_jTxtCodigo;
    private javax.swing.JTextField mml_jTxtCpf;
    private javax.swing.JTextField mml_jTxtCredencial;
    private javax.swing.JTextField mml_jTxtDataNasc;
    private javax.swing.JTextField mml_jTxtExpediente;
    private javax.swing.JTextField mml_jTxtNome;
    // End of variables declaration//GEN-END:variables
}
