/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;


import bean.MmlUsuarios;
import dao.MmlUsuariosDao;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import tools.Util;

/**
 *
 * @author Marlon
 */
public class MmljDlgUsuario extends javax.swing.JDialog { 
    
  private boolean incluir;
    /**
     * Creates new form jDlgUsuario
     */
    public MmljDlgUsuario(java.awt.Frame parent, boolean modal) {
      super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Cadastro de usuarios");
         Util.habilitar(false,mmljTxtNome,mmljTxtCodigo,mmljFmtDataNascimento,mmljPwdSenha ,mmljCboNivel,  mmljChbAtivo, mmljTxtApelido, mmljFmtCpf,mmljBtnPesquisar,mmljBtnCancelar, mmljBtnExcluir,mmljBtnAlterar);
    }

    
      
   public MmlUsuarios viewBean() {
    MmlUsuarios mmlUsuarios = new MmlUsuarios();
    int codigo = Util.strToInt(mmljTxtCodigo.getText());
    mmlUsuarios.setMmlIdUsusario(codigo);
    mmlUsuarios.setMmlNome(mmljTxtNome.getText());
    mmlUsuarios.setMmlApelido(mmljTxtApelido.getText());
    mmlUsuarios.setMmlCpf(mmljFmtCpf.getText());
    mmlUsuarios.setMmlSenha(mmljPwdSenha.getText());
    mmlUsuarios.setMmlNivel(mmljCboNivel.getSelectedIndex()); 
    mmlUsuarios.setMmlAtivo(mmljChbAtivo.isSelected() ? "S" : "N");
    mmlUsuarios.setMmlDataNas(Util.strToDate(mmljFmtDataNascimento.getText()));
    return mmlUsuarios;
}

public void beanView(MmlUsuarios mmlUsuarios) {
    mmljTxtCodigo.setText(Util.intToStr(mmlUsuarios.getMmlIdUsusario()));
    mmljTxtNome.setText(mmlUsuarios.getMmlNome());
    mmljTxtApelido.setText(mmlUsuarios.getMmlApelido());
    mmljFmtCpf.setText(mmlUsuarios.getMmlCpf());
    mmljPwdSenha.setText(mmlUsuarios.getMmlSenha());
    mmljCboNivel.setSelectedIndex(mmlUsuarios.getMmlNivel()); 
    mmljChbAtivo.setSelected("S".equals(mmlUsuarios.getMmlAtivo()));
    mmljFmtDataNascimento.setText(Util.dateToStr(mmlUsuarios.getMmlDataNas()));
}


   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mmljLblNome = new javax.swing.JLabel();
        mmljTxtNome = new javax.swing.JTextField();
        mmljLblApelido = new javax.swing.JLabel();
        mmljTxtApelido = new javax.swing.JTextField();
        mmlJLblCodigo = new javax.swing.JLabel();
        mmljTxtCodigo = new javax.swing.JTextField();
        mmljLblCpf = new javax.swing.JLabel();
        mmljFmtCpf = new javax.swing.JTextField();
        mmlJLblDataNasc = new javax.swing.JLabel();
        mmljFmtDataNascimento = new javax.swing.JTextField();
        mmljLblSenha = new javax.swing.JLabel();
        mmljPwdSenha = new javax.swing.JTextField();
        mmlJLblNivel = new javax.swing.JLabel();
        mmljCboNivel = new javax.swing.JComboBox<>();
        mmljBtnIncluir = new javax.swing.JButton();
        mmljBtnAlterar = new javax.swing.JButton();
        mmljBtnExcluir = new javax.swing.JButton();
        mmljBtnConfirmar = new javax.swing.JButton();
        mmljBtnCancelar = new javax.swing.JButton();
        mmljBtnPesquisar = new javax.swing.JButton();
        mmljLblAtivo = new javax.swing.JLabel();
        mmljChbAtivo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mmljLblNome.setText("Nome");

        mmljTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmljTxtNomeActionPerformed(evt);
            }
        });

        mmljLblApelido.setText("Apelido");

        mmlJLblCodigo.setText("Código");

        mmljTxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmljTxtCodigoActionPerformed(evt);
            }
        });

        mmljLblCpf.setText("Cpf");

        mmlJLblDataNasc.setText("Data de Nascimento");

        mmljFmtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmljFmtDataNascimentoActionPerformed(evt);
            }
        });

        mmljLblSenha.setText("Senha");

        mmlJLblNivel.setText("Nível");

        mmljCboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Cliente", "Vendedor", "Item 4" }));
        mmljCboNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmljCboNivelActionPerformed(evt);
            }
        });

        mmljBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        mmljBtnIncluir.setText("Incluir");
        mmljBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmljBtnIncluirActionPerformed(evt);
            }
        });

        mmljBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        mmljBtnAlterar.setText("Alterar");
        mmljBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmljBtnAlterarActionPerformed(evt);
            }
        });

        mmljBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        mmljBtnExcluir.setText("Excluir");
        mmljBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmljBtnExcluirActionPerformed(evt);
            }
        });

        mmljBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        mmljBtnConfirmar.setText("Confirmar");
        mmljBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmljBtnConfirmarActionPerformed(evt);
            }
        });

        mmljBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        mmljBtnCancelar.setText("Cancelar");
        mmljBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmljBtnCancelarActionPerformed(evt);
            }
        });

        mmljBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar (2)_1.png"))); // NOI18N
        mmljBtnPesquisar.setText("Pesquisar");
        mmljBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmljBtnPesquisarActionPerformed(evt);
            }
        });

        mmljLblAtivo.setText("Ativo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mmljBtnIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mmljBtnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mmljBtnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mmljBtnConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mmljBtnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mmljBtnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(mmljFmtDataNascimento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                        .addComponent(mmljTxtCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mmljTxtNome, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(mmlJLblDataNasc))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(215, 215, 215)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mmljTxtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mmljFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mmljChbAtivo)
                                            .addComponent(mmljLblAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mmljLblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mmlJLblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mmlJLblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(137, 137, 137)
                                .addComponent(mmljLblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mmljPwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mmljLblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140)
                                .addComponent(mmljLblApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mmljCboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(149, 149, 149))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mmljLblNome)
                    .addComponent(mmljLblApelido)
                    .addComponent(mmljLblSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mmljTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mmljTxtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mmljPwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mmlJLblCodigo)
                    .addComponent(mmljLblCpf)
                    .addComponent(mmlJLblNivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mmljTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mmljFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mmljCboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mmlJLblDataNasc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mmljFmtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mmljLblAtivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mmljChbAtivo)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mmljBtnIncluir)
                    .addComponent(mmljBtnAlterar)
                    .addComponent(mmljBtnConfirmar)
                    .addComponent(mmljBtnCancelar)
                    .addComponent(mmljBtnPesquisar)
                    .addComponent(mmljBtnExcluir))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mmljTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmljTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mmljTxtNomeActionPerformed

    private void mmljTxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmljTxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mmljTxtCodigoActionPerformed

    private void mmljFmtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmljFmtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mmljFmtDataNascimentoActionPerformed

    private void mmljCboNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmljCboNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mmljCboNivelActionPerformed

    private void mmljBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmljBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (Util.perguntar("Excluir?") == true) {
            MmlUsuariosDao mmlUsuariosDao = new MmlUsuariosDao();
            mmlUsuariosDao.delete(viewBean());
            Util.habilitar(false, mmljBtnAlterar, mmljBtnCancelar, mmljBtnExcluir);
            Util.habilitar(true, mmljBtnIncluir, mmljBtnPesquisar);
            Util.limpar(mmljTxtNome,mmljTxtApelido,mmljFmtCpf, mmljPwdSenha,mmljCboNivel,mmljChbAtivo, mmljFmtDataNascimento, mmljTxtCodigo);
        }
        
        
    }//GEN-LAST:event_mmljBtnExcluirActionPerformed

    private void mmljBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmljBtnIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, mmljTxtNome,mmljTxtApelido,mmljFmtCpf, mmljPwdSenha,mmljCboNivel,mmljChbAtivo, mmljFmtDataNascimento, mmljTxtCodigo,  mmljBtnConfirmar, mmljBtnCancelar);
        Util.habilitar(false, mmljBtnIncluir, mmljBtnPesquisar);
        Util.limpar( mmljTxtNome,mmljTxtApelido,mmljFmtCpf, mmljPwdSenha,mmljCboNivel,mmljChbAtivo, mmljFmtDataNascimento, mmljTxtCodigo);
        mmljTxtNome.grabFocus();
        
    }//GEN-LAST:event_mmljBtnIncluirActionPerformed

    private void mmljBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmljBtnConfirmarActionPerformed
        // TODO add your handling code here:
        MmlUsuariosDao mmlUsuariosDao = new MmlUsuariosDao();
        if (incluir) {
            mmlUsuariosDao.insert(viewBean());
        } else {
            mmlUsuariosDao.update(viewBean());
        }
        Util.habilitar(false,mmljTxtNome,mmljTxtApelido,mmljFmtCpf, mmljPwdSenha,mmljCboNivel,mmljChbAtivo, mmljFmtDataNascimento, mmljTxtCodigo,  mmljBtnConfirmar, mmljBtnCancelar, mmljBtnConfirmar, mmljBtnCancelar,  mmljBtnConfirmar, mmljBtnCancelar);
        Util.habilitar(true, mmljBtnIncluir, mmljBtnPesquisar);
        Util.limpar(mmljTxtNome,mmljTxtApelido,mmljFmtCpf, mmljPwdSenha,mmljCboNivel,mmljChbAtivo, mmljFmtDataNascimento, mmljTxtCodigo,  mmljBtnConfirmar, mmljBtnCancelar);
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_mmljBtnConfirmarActionPerformed

    private void mmljBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmljBtnCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false,mmljTxtNome,mmljTxtApelido,mmljFmtCpf, mmljPwdSenha,mmljCboNivel,mmljChbAtivo, mmljFmtDataNascimento, mmljTxtCodigo,  mmljBtnConfirmar, mmljBtnCancelar, mmljBtnConfirmar, mmljBtnCancelar,  mmljBtnConfirmar, mmljBtnCancelar);
        Util.habilitar(true, mmljBtnIncluir, mmljBtnPesquisar);
        Util.limpar(mmljTxtNome,mmljTxtApelido,mmljFmtCpf, mmljPwdSenha,mmljCboNivel,mmljChbAtivo, mmljFmtDataNascimento, mmljTxtCodigo,  mmljBtnConfirmar, mmljBtnCancelar);
      
    }//GEN-LAST:event_mmljBtnCancelarActionPerformed

    private void mmljBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmljBtnPesquisarActionPerformed
        // TODO add your handling code here:
        Mml_jDlgUsuariosPesquisar dlgUsuariosPesquisar = new Mml_jDlgUsuariosPesquisar(null,true);
        dlgUsuariosPesquisar.setTelaPai(this);
        dlgUsuariosPesquisar.setVisible(true);
       
      
      
    }//GEN-LAST:event_mmljBtnPesquisarActionPerformed

    private void mmljBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmljBtnAlterarActionPerformed
        // TODO add your handling code here:
        incluir = false;
        Util.habilitar(true, mmljTxtNome,mmljTxtApelido,mmljFmtCpf, mmljPwdSenha,mmljCboNivel,mmljChbAtivo, mmljFmtDataNascimento, mmljTxtCodigo,  mmljBtnConfirmar, mmljBtnCancelar);
        Util.habilitar(false, mmljBtnExcluir, mmljBtnIncluir, mmljBtnAlterar);
        mmljTxtNome.grabFocus();
        
        
    }//GEN-LAST:event_mmljBtnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MmljDlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MmljDlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MmljDlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MmljDlgUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MmljDlgUsuario dialog = new MmljDlgUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel mmlJLblCodigo;
    private javax.swing.JLabel mmlJLblDataNasc;
    private javax.swing.JLabel mmlJLblNivel;
    private javax.swing.JButton mmljBtnAlterar;
    private javax.swing.JButton mmljBtnCancelar;
    private javax.swing.JButton mmljBtnConfirmar;
    private javax.swing.JButton mmljBtnExcluir;
    private javax.swing.JButton mmljBtnIncluir;
    private javax.swing.JButton mmljBtnPesquisar;
    private javax.swing.JComboBox<String> mmljCboNivel;
    private javax.swing.JCheckBox mmljChbAtivo;
    private javax.swing.JTextField mmljFmtCpf;
    private javax.swing.JTextField mmljFmtDataNascimento;
    private javax.swing.JLabel mmljLblApelido;
    private javax.swing.JLabel mmljLblAtivo;
    private javax.swing.JLabel mmljLblCpf;
    private javax.swing.JLabel mmljLblNome;
    private javax.swing.JLabel mmljLblSenha;
    private javax.swing.JTextField mmljPwdSenha;
    private javax.swing.JTextField mmljTxtApelido;
    private javax.swing.JTextField mmljTxtCodigo;
    private javax.swing.JTextField mmljTxtNome;
    // End of variables declaration//GEN-END:variables
}
