/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;


import bean.MmlCliente;
import bean.MmlVendas;
import bean.MmlVendedor;
import dao.MmlClienteDao;
import dao.MmlUsuariosDao;
import dao.MmlVendasDao;
import dao.MmlVendedorDao;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import tools.Util;


/**
 *
 * @author Marlon
 */
public class MmljDlgVendas extends javax.swing.JDialog {
     Mm_Controller_Vendas_Carros mm_Controller_Vendas_Carros;
     private boolean incluir;
    /**
     * Creates new form MmljDlgVendas
     */
    public MmljDlgVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Cadastro de Vendedor");
        Util.habilitar(false, mml_jTxtIdVendas, mml_jcboClientes, mml_jTxtValor, mml_jTxtFormasdePagamento, mml_jTxtData, mml_jcboVendedor, mml_jBtnIncluir, mml_jBtnCancelar, mml_jBtnIncluirProd, mml_jBtnAlterarProd, mml_jBtnExcluirProd);
        Util.habilitar(true, mml_jBtnIncluir, mml_jBtnAlterar, mml_jBtnExcluir, mml_jBtnPesquisar);

        MmlClienteDao clientesDAO = new MmlClienteDao();
        List lista = (List) clientesDAO.listAll();
            for(int i = 0; i < lista.size(); i++){
            mml_jcboClientes.addItem((MmlCliente)lista.get(i));
        }

        MmlVendedorDao vendedorDAO = new MmlVendedorDao();
            for(int i = 0; i < lista.size(); i++){
            mml_jcboVendedor.addItem((MmlVendedor)lista.get(i));
        }
        mm_Controller_Vendas_Carros = new Mm_Controller_Vendas_Carros();
        mm_Controller_Vendas_Carros.setList(new ArrayList());
        jTable1.setModel(mm_Controller_Vendas_Carros);
    }
  public MmlVendas viewBean() {
        MmlVendas vendas = new MmlVendas();
        vendas.setMmlIdVendas(Util.strToInt(mml_jTxtIdVendas.getText()));
        vendas.setMmlCliente((MmlCliente) mml_jcboClientes.getSelectedItem() );
        vendas.setMmlVendedor((MmlVendedor) mml_jcboVendedor.getSelectedItem());
        vendas.setMmlValor(Util.strToDouble(mml_jTxtValor.getText()));
        return vendas;
    }
    
    public void beanView(MmlVendas vendas) {
        mml_jcboClientes.setSelectedItem(vendas.getMmlCliente());
    }

    public void habilitar (boolean value){
      mml_jTxtIdVendas.setEnabled(value);
      mml_jTxtIdVendas.setEnabled(value);
      mml_jTxtValor.setEnabled(value);
      mml_jTxtFormasdePagamento.setEnabled(value);
      mml_jTxtData.setEnabled(value);
      
      
      
      
      mml_jBtnIncluir.setEnabled(!value);
      mml_jBtnAlterar.setEnabled(!value);
      mml_jBtnExcluir.setEnabled(!value);
      mml_jBtnConfirmar.setEnabled(value);
      mml_jBtnCancelar.setEnabled(value);
      mml_jBtnPesquisar.setEnabled(!value);

      
}
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mml_jLblFormasdePagamento = new javax.swing.JLabel();
        mml_jBtnExcluir = new javax.swing.JButton();
        mml_jTxtFormasdePagamento = new javax.swing.JTextField();
        mml_jBtnConfirmar = new javax.swing.JButton();
        mml_jBtnCancelar = new javax.swing.JButton();
        mml_jLblData = new javax.swing.JLabel();
        mml_jLblIdVendas = new javax.swing.JLabel();
        mml_jTxtData = new javax.swing.JTextField();
        mml_jTxtIdVendas = new javax.swing.JTextField();
        mml_jLblIdClientes = new javax.swing.JLabel();
        mml_jBtnPesquisar = new javax.swing.JButton();
        mml_jLblValor = new javax.swing.JLabel();
        mml_jBtnIncluir = new javax.swing.JButton();
        mml_jTxtValor = new javax.swing.JTextField();
        mml_jBtnAlterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        mml_jLblIdVendedor = new javax.swing.JLabel();
        mml_jcboVendedor = new javax.swing.JComboBox<MmlVendedor>();
        mml_jcboClientes = new javax.swing.JComboBox<MmlCliente>();
        mml_jBtnIncluirProd = new javax.swing.JButton();
        mml_jBtnAlterarProd = new javax.swing.JButton();
        mml_jBtnExcluirProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mml_jLblFormasdePagamento.setText("Forma Pagamento");

        mml_jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        mml_jBtnExcluir.setText("Excluir");
        mml_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnExcluirActionPerformed(evt);
            }
        });

        mml_jTxtFormasdePagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtFormasdePagamentoActionPerformed(evt);
            }
        });

        mml_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        mml_jBtnConfirmar.setText("Confirmar");
        mml_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnConfirmarActionPerformed(evt);
            }
        });

        mml_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        mml_jBtnCancelar.setText("Cancelar");
        mml_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnCancelarActionPerformed(evt);
            }
        });

        mml_jLblData.setText("Data");

        mml_jLblIdVendas.setText("Id Vendas");

        mml_jTxtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtDataActionPerformed(evt);
            }
        });

        mml_jTxtIdVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtIdVendasActionPerformed(evt);
            }
        });

        mml_jLblIdClientes.setText("Id Cliente");

        mml_jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar (2)_1.png"))); // NOI18N
        mml_jBtnPesquisar.setText("Pesquisar");
        mml_jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnPesquisarActionPerformed(evt);
            }
        });

        mml_jLblValor.setText("Valor");

        mml_jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        mml_jBtnIncluir.setText("Incluir");
        mml_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnIncluirActionPerformed(evt);
            }
        });

        mml_jTxtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtValorActionPerformed(evt);
            }
        });

        mml_jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        mml_jBtnAlterar.setText("Alterar");
        mml_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnAlterarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        mml_jLblIdVendedor.setText("id vendedor");

        mml_jBtnIncluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        mml_jBtnIncluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnIncluirProdActionPerformed(evt);
            }
        });

        mml_jBtnAlterarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        mml_jBtnAlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnAlterarProdActionPerformed(evt);
            }
        });

        mml_jBtnExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        mml_jBtnExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnExcluirProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(mml_jTxtFormasdePagamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(mml_jTxtIdVendas, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mml_jLblIdVendas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mml_jLblFormasdePagamento))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mml_jLblIdClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mml_jcboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mml_jLblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mml_jTxtValor)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mml_jLblData, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(mml_jLblIdVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(mml_jTxtData, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jBtnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jBtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jBtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jBtnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jBtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jBtnPesquisar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(mml_jcboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mml_jBtnIncluirProd)
                            .addComponent(mml_jBtnAlterarProd)
                            .addComponent(mml_jBtnExcluirProd))
                        .addGap(29, 29, 29)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblIdClientes)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblIdVendas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mml_jTxtIdVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mml_jcboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(mml_jBtnIncluirProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mml_jBtnAlterarProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mml_jBtnExcluirProd)
                        .addContainerGap(450, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mml_jLblFormasdePagamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mml_jTxtFormasdePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mml_jTxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(mml_jcboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(mml_jLblData)
                                    .addComponent(mml_jLblIdVendedor))
                                .addGap(29, 29, 29)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mml_jBtnAlterar)
                            .addComponent(mml_jBtnExcluir)
                            .addComponent(mml_jBtnConfirmar)
                            .addComponent(mml_jBtnCancelar)
                            .addComponent(mml_jBtnPesquisar)
                            .addComponent(mml_jBtnIncluir))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mml_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if(Util.perguntar("Deseja excluir o registro?") == true) {
            MmlVendasDao mmlVendasDao = new MmlVendasDao();
            mmlVendasDao.delete(viewBean());
            Util.limpar(mml_jTxtIdVendas, mml_jTxtValor, mml_jTxtFormasdePagamento, mml_jTxtData, mml_jcboClientes, mml_jcboVendedor);
        }
    }//GEN-LAST:event_mml_jBtnExcluirActionPerformed

    private void mml_jTxtFormasdePagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtFormasdePagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtFormasdePagamentoActionPerformed

    private void mml_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
       MmlVendasDao mmlVendasDao = new MmlVendasDao();
        if (incluir) {
            mmlVendasDao.insert(viewBean());
        } else {
            mmlVendasDao.update(viewBean());
        }
        Util.habilitar(false,mml_jTxtIdVendas, mml_jTxtValor, mml_jTxtFormasdePagamento, mml_jTxtData, mml_jcboClientes, mml_jcboVendedor,  mml_jBtnIncluir, mml_jBtnCancelar, mml_jBtnConfirmar, mml_jBtnCancelar,  mml_jBtnConfirmar, mml_jBtnCancelar);
        Util.habilitar(true, mml_jBtnIncluir, mml_jBtnPesquisar);
        Util.limpar(mml_jTxtIdVendas, mml_jTxtValor, mml_jTxtFormasdePagamento, mml_jTxtData, mml_jcboClientes, mml_jcboVendedor,  mml_jBtnConfirmar, mml_jBtnCancelar);
        // TODO add your handling code here:

    }//GEN-LAST:event_mml_jBtnConfirmarActionPerformed

    private void mml_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, mml_jTxtIdVendas, mml_jTxtValor, mml_jTxtFormasdePagamento, mml_jTxtData, mml_jcboClientes, mml_jcboVendedor, mml_jBtnConfirmar, mml_jBtnCancelar);
        Util.habilitar(false, mml_jBtnIncluir, mml_jBtnPesquisar);
        
        
    }//GEN-LAST:event_mml_jBtnCancelarActionPerformed

    private void mml_jTxtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtDataActionPerformed

    private void mml_jTxtIdVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtIdVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtIdVendasActionPerformed

    private void mml_jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, mml_jBtnIncluir, mml_jBtnPesquisar);
        Mml_jDlgVendasPesquisar jDlgUsuariosPesquisar = new Mml_jDlgVendasPesquisar(null, true);
        jDlgUsuariosPesquisar.setTelaPai(this);
        jDlgUsuariosPesquisar.setVisible(true);
       
      

    }//GEN-LAST:event_mml_jBtnPesquisarActionPerformed

    private void mml_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, mml_jTxtIdVendas, mml_jTxtValor, mml_jTxtFormasdePagamento, mml_jTxtData, mml_jcboClientes, mml_jcboVendedor, mml_jBtnConfirmar, mml_jBtnCancelar, mml_jBtnAlterarProd, mml_jBtnExcluirProd, mml_jBtnIncluirProd);
        Util.habilitar(false, mml_jBtnIncluir, mml_jBtnPesquisar);
        Util.limpar(mml_jTxtIdVendas, mml_jTxtValor, mml_jTxtFormasdePagamento, mml_jTxtData, mml_jcboClientes, mml_jcboVendedor);
        mml_jTxtIdVendas.grabFocus();
        
    }//GEN-LAST:event_mml_jBtnIncluirActionPerformed

    private void mml_jTxtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtValorActionPerformed

    private void mml_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, mml_jTxtIdVendas, mml_jTxtValor, mml_jTxtFormasdePagamento, mml_jTxtData, mml_jcboClientes, mml_jcboVendedor, mml_jBtnConfirmar, mml_jBtnCancelar);
        Util.habilitar(false, mml_jBtnIncluir, mml_jBtnPesquisar);
        Util.limpar(mml_jTxtIdVendas, mml_jTxtValor, mml_jTxtFormasdePagamento, mml_jTxtData, mml_jcboClientes, mml_jcboVendedor);
        mml_jTxtFormasdePagamento.grabFocus();
    }//GEN-LAST:event_mml_jBtnAlterarActionPerformed

    private void mml_jBtnIncluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnIncluirProdActionPerformed
        // TODO add your handling code here:
        
        MmljDlgVendasCarros jDlgMmlVendasProdutos = new MmljDlgVendasCarros(null, true);
        jDlgMmlVendasProdutos.setTelaAnterior(this);
        jDlgMmlVendasProdutos.setVisible(true);
        
    }//GEN-LAST:event_mml_jBtnIncluirProdActionPerformed

    private void mml_jBtnAlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnAlterarProdActionPerformed
        // TODO add your handling code here:
        MmljDlgVendasCarros mmljDlgVendasCarros = new MmljDlgVendasCarros(null, true);
        mmljDlgVendasCarros.setVisible(true);
    }//GEN-LAST:event_mml_jBtnAlterarProdActionPerformed

    private void mml_jBtnExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnExcluirProdActionPerformed
        // TODO add your handling code here:
        int rowIndex = jTable1.getSelectedRow();
                if (rowIndex == -1) {
                    Util.mensagem("Selecione alguma linha primeiro");
                    return;
                }
                if (Util.perguntar("Deseja Excluir?") == true) {
                    mm_Controller_Vendas_Carros.removeBean(rowIndex);
       
                }
    }//GEN-LAST:event_mml_jBtnExcluirProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MmljDlgVendas dialog = new MmljDlgVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton mml_jBtnAlterar;
    private javax.swing.JButton mml_jBtnAlterarProd;
    private javax.swing.JButton mml_jBtnCancelar;
    private javax.swing.JButton mml_jBtnConfirmar;
    private javax.swing.JButton mml_jBtnExcluir;
    private javax.swing.JButton mml_jBtnExcluirProd;
    private javax.swing.JButton mml_jBtnIncluir;
    private javax.swing.JButton mml_jBtnIncluirProd;
    private javax.swing.JButton mml_jBtnPesquisar;
    private javax.swing.JLabel mml_jLblData;
    private javax.swing.JLabel mml_jLblFormasdePagamento;
    private javax.swing.JLabel mml_jLblIdClientes;
    private javax.swing.JLabel mml_jLblIdVendas;
    private javax.swing.JLabel mml_jLblIdVendedor;
    private javax.swing.JLabel mml_jLblValor;
    private javax.swing.JTextField mml_jTxtData;
    private javax.swing.JTextField mml_jTxtFormasdePagamento;
    private javax.swing.JTextField mml_jTxtIdVendas;
    private javax.swing.JTextField mml_jTxtValor;
    private javax.swing.JComboBox<MmlCliente> mml_jcboClientes;
    private javax.swing.JComboBox<MmlVendedor> mml_jcboVendedor;
    // End of variables declaration//GEN-END:variables
}
