package bean;
// Generated 21/11/2025 20:16:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MmlCliente generated by hbm2java
 */
@Entity
@Table(name="mml_cliente"
    ,catalog="db_miguel_leal"
)
public class MmlCliente  implements java.io.Serializable {


     private int mmlIdCliente;
     private String mmlNome;
     private String mmlRg;
     private String mmlSexo;
     private String mmlAtivo;
     private String mmlCpf;
     private Date mmlDataCadastro;
     private String mmlTelefone;
     private String mmlCelular;
     private Date mmlDatanascimento;
     private String mmlEnderoco;
     private String mmlEmail;
     private String mmlCidade;
     private String mmlCep;
     private String mmlBairro;
     

    public MmlCliente() {
    }

    public MmlCliente(String mmlNome, String mmlRg, String mmlSexo, String mmlAtivo, String mmlCpf, Date mmlDataCadastro, String mmlTelefone, String mmlCelular, Date mmlDatanascimento, String mmlEnderoco, String mmlEmail, String mmlCidade, String mmlCep, String mmlBairro) {
       this.mmlNome = mmlNome;
       this.mmlRg = mmlRg;
       this.mmlSexo = mmlSexo;
       this.mmlAtivo = mmlAtivo;
       this.mmlCpf = mmlCpf;
       this.mmlDataCadastro = mmlDataCadastro;
       this.mmlTelefone = mmlTelefone;
       this.mmlCelular = mmlCelular;
       this.mmlDatanascimento = mmlDatanascimento;
       this.mmlEnderoco = mmlEnderoco;
       this.mmlEmail = mmlEmail;
       this.mmlCidade = mmlCidade;
       this.mmlCep = mmlCep;
       this.mmlBairro = mmlBairro;
       
    }
   
     @Id 

    
    @Column(name="mml_idCliente", unique=true, nullable=false)
    public int getMmlIdCliente() {
        return this.mmlIdCliente;
    }
    
    public void setMmlIdCliente(int mmlIdCliente) {
        this.mmlIdCliente = mmlIdCliente;
    }

    
    @Column(name="mml_nome", length=80)
    public String getMmlNome() {
        return this.mmlNome;
    }
    
    public void setMmlNome(String mmlNome) {
        this.mmlNome = mmlNome;
    }

    
    @Column(name="mml_rg", length=10)
    public String getMmlRg() {
        return this.mmlRg;
    }
    
    public void setMmlRg(String mmlRg) {
        this.mmlRg = mmlRg;
    }

    
    @Column(name="mml_sexo", length=1)
    public String getMmlSexo() {
        return this.mmlSexo;
    }
    
    public void setMmlSexo(String mmlSexo) {
        this.mmlSexo = mmlSexo;
    }

    
    @Column(name="mml_ativo", length=1)
    public String getMmlAtivo() {
        return this.mmlAtivo;
    }
    
    public void setMmlAtivo(String mmlAtivo) {
        this.mmlAtivo = mmlAtivo;
    }

    
    @Column(name="mml_cpf", length=14)
    public String getMmlCpf() {
        return this.mmlCpf;
    }
    
    public void setMmlCpf(String mmlCpf) {
        this.mmlCpf = mmlCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mml_dataCadastro", length=10)
    public Date getMmlDataCadastro() {
        return this.mmlDataCadastro;
    }
    
    public void setMmlDataCadastro(Date mmlDataCadastro) {
        this.mmlDataCadastro = mmlDataCadastro;
    }

    
    @Column(name="mml_telefone", length=10)
    public String getMmlTelefone() {
        return this.mmlTelefone;
    }
    
    public void setMmlTelefone(String mmlTelefone) {
        this.mmlTelefone = mmlTelefone;
    }

    
    @Column(name="mml_celular", length=10)
    public String getMmlCelular() {
        return this.mmlCelular;
    }
    
    public void setMmlCelular(String mmlCelular) {
        this.mmlCelular = mmlCelular;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mml_datanascimento", length=10)
    public Date getMmlDatanascimento() {
        return this.mmlDatanascimento;
    }
    
    public void setMmlDatanascimento(Date mmlDatanascimento) {
        this.mmlDatanascimento = mmlDatanascimento;
    }

    
    @Column(name="mml_enderoco", length=70)
    public String getMmlEnderoco() {
        return this.mmlEnderoco;
    }
    
    public void setMmlEnderoco(String mmlEnderoco) {
        this.mmlEnderoco = mmlEnderoco;
    }

    
    @Column(name="mml_email", length=80)
    public String getMmlEmail() {
        return this.mmlEmail;
    }
    
    public void setMmlEmail(String mmlEmail) {
        this.mmlEmail = mmlEmail;
    }

    
    @Column(name="mml_cidade", length=30)
    public String getMmlCidade() {
        return this.mmlCidade;
    }
    
    public void setMmlCidade(String mmlCidade) {
        this.mmlCidade = mmlCidade;
    }

    
    @Column(name="mml_cep", length=9)
    public String getMmlCep() {
        return this.mmlCep;
    }
    
    public void setMmlCep(String mmlCep) {
        this.mmlCep = mmlCep;
    }

    
    @Column(name="mml_bairro", length=20)
    public String getMmlBairro() {
        return this.mmlBairro;
    }
    
    public void setMmlBairro(String mmlBairro) {
        this.mmlBairro = mmlBairro;
    }


 @Override
    public String toString(){
        return this.mmlNome;
    }
    
     @Override
        public boolean equals(Object object){
        if (object instanceof MmlCliente){
            MmlCliente clientes = (MmlCliente)object;
            if (this.getMmlIdCliente()== clientes.getMmlIdCliente()){
                return true;
            }
        }
         return false;
    }
}
