package bean;
// Generated 10/10/2025 16:46:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MmlCarros generated by hbm2java
 */
@Entity
@Table(name="mml_carros"
    ,catalog="db_miguel_leal"
)
public class MmlCarros  implements java.io.Serializable {


     private int mmlIdCarros;
     private String mmlModelo;
     private String mmlMarca;
     private String mmlCor;
     private Date mmlAno;
     private double mmlPreco;
     private double mmlPrecoVenda;

    public MmlCarros() {
    }

	
    public MmlCarros(String mmlModelo, String mmlMarca, String mmlCor, double mmlPreco, double mmlPrecoVenda) {
        this.mmlModelo = mmlModelo;
        this.mmlMarca = mmlMarca;
        this.mmlCor = mmlCor;
        this.mmlPreco = mmlPreco;
        this.mmlPrecoVenda = mmlPrecoVenda;
    }
    public MmlCarros(String mmlModelo, String mmlMarca, String mmlCor, Date mmlAno, double mmlPreco, double mmlPrecoVenda, Set mmlVendasCarroses) {
       this.mmlModelo = mmlModelo;
       this.mmlMarca = mmlMarca;
       this.mmlCor = mmlCor;
       this.mmlAno = mmlAno;
       this.mmlPreco = mmlPreco;
       this.mmlPrecoVenda = mmlPrecoVenda;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="mml_idCarros", unique=true, nullable=false)
    public int getMmlIdCarros() {
        return this.mmlIdCarros;
    }
    
    public void setMmlIdCarros(int mmlIdCarros) {
        this.mmlIdCarros = mmlIdCarros;
    }

    
    @Column(name="mml_modelo", nullable=false, length=50)
    public String getMmlModelo() {
        return this.mmlModelo;
    }
    
    public void setMmlModelo(String mmlModelo) {
        this.mmlModelo = mmlModelo;
    }

    
    @Column(name="mml_marca", nullable=false, length=50)
    public String getMmlMarca() {
        return this.mmlMarca;
    }
    
    public void setMmlMarca(String mmlMarca) {
        this.mmlMarca = mmlMarca;
    }

    
    @Column(name="mml_cor", nullable=false, length=15)
    public String getMmlCor() {
        return this.mmlCor;
    }
    
    public void setMmlCor(String mmlCor) {
        this.mmlCor = mmlCor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mml_ano", length=10)
    public Date getMmlAno() {
        return this.mmlAno;
    }
    
    public void setMmlAno(Date mmlAno) {
        this.mmlAno = mmlAno;
    }

    
    @Column(name="mml_preco", nullable=false, precision=10)
    public double getMmlPreco() {
        return this.mmlPreco;
    }
    
    public void setMmlPreco(double mmlPreco) {
        this.mmlPreco = mmlPreco;
    }

    
    @Column(name="mml_precoVenda", nullable=false, precision=10)
    public double getMmlPrecoVenda() {
        return this.mmlPrecoVenda;
    }
    
    public void setMmlPrecoVenda(double mmlPrecoVenda) {
        this.mmlPrecoVenda = mmlPrecoVenda;
    }



}


