package bean;
// Generated 10/10/2025 16:46:28 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MmlUsuarios generated by hbm2java
 */
@Entity
@Table(name="mml_usuarios"
    ,catalog="db_miguel_leal"
)
public class MmlUsuarios  implements java.io.Serializable {


     private int mmlIdUsusario;
     private String mmlNome;
     private String mmlApelido;
     private String mmlCpf;
     private String mmlSenha;
     private int mmlNivel;
     private Date mmlDataNas;
     private String mmlAtivo;

    public MmlUsuarios() {
    }

    public MmlUsuarios(String mmlNome, String mmlApelido, String mmlCpf, String mmlSenha, int mmlNivel, Date mmlDataNas, String mmlAtivo) {
       this.mmlNome = mmlNome;
       this.mmlApelido = mmlApelido;
       this.mmlCpf = mmlCpf;
       this.mmlSenha = mmlSenha;
       this.mmlNivel = mmlNivel;
       this.mmlDataNas = mmlDataNas;
       this.mmlAtivo = mmlAtivo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="mml_idUsusario", unique=true, nullable=false)
    public int getMmlIdUsusario() {
        return this.mmlIdUsusario;
    }
    
    public void setMmlIdUsusario(int mmlIdUsusario) {
        this.mmlIdUsusario = mmlIdUsusario;
    }

    
    @Column(name="mml_nome", length=50)
    public String getMmlNome() {
        return this.mmlNome;
    }
    
    public void setMmlNome(String mmlNome) {
        this.mmlNome = mmlNome;
    }

    
    @Column(name="mml_apelido", length=25)
    public String getMmlApelido() {
        return this.mmlApelido;
    }
    
    public void setMmlApelido(String mmlApelido) {
        this.mmlApelido = mmlApelido;
    }

    
    @Column(name="mml_cpf", length=14)
    public String getMmlCpf() {
        return this.mmlCpf;
    }
    
    public void setMmlCpf(String mmlCpf) {
        this.mmlCpf = mmlCpf;
    }

    
    @Column(name="mml_senha", length=20)
    public String getMmlSenha() {
        return this.mmlSenha;
    }
    
    public void setMmlSenha(String mmlSenha) {
        this.mmlSenha = mmlSenha;
    }

    
    @Column(name="mml_nivel")
    public int getMmlNivel() {
        return this.mmlNivel;
    }
    
    public void setMmlNivel(int mmlNivel) {
        this.mmlNivel = mmlNivel;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mml_dataNas", length=10)
    public Date getMmlDataNas() {
        return this.mmlDataNas;
    }
    
    public void setMmlDataNas(Date mmlDataNas) {
        this.mmlDataNas = mmlDataNas;
    }

    
    @Column(name="mml_ativo", length=1)
    public String getMmlAtivo() {
        return this.mmlAtivo;
    }
    
    public void setMmlAtivo(String mmlAtivo) {
        this.mmlAtivo = mmlAtivo;
    }




}


