package bean;
// Generated 21/11/2025 20:16:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MmlVendas generated by hbm2java
 */
@Entity
@Table(name="mml_vendas"
    ,catalog="db_miguel_leal"
)
public class MmlVendas  implements java.io.Serializable {


     private int mmlIdVendas;
     private MmlCliente mmlCliente;
     private MmlVendedor mmlVendedor;
     private Date mmlData;
     private double mmlValor;
     private String mmlQuantidade;
     

    public MmlVendas() {
    }

	
    public MmlVendas(MmlCliente mmlCliente) {
        this.mmlCliente = mmlCliente;
    }
    
    public MmlVendas(MmlVendedor mmlVendedor) {
        this.mmlVendedor = mmlVendedor;
    }
    
    public MmlVendas(MmlCliente mmlCliente, Date mmlData, double mmlValor, String mmlQuantidade) {
       this.mmlCliente = mmlCliente;
       this.mmlVendedor = mmlVendedor;
       this.mmlData = mmlData;
       this.mmlValor = mmlValor;
       this.mmlQuantidade = mmlQuantidade;
       
    }
   
     @Id 

    
    @Column(name="mml_idVendas", unique=true, nullable=false)
    public int getMmlIdVendas() {
        return this.mmlIdVendas;
    }
    
    public void setMmlIdVendas(int mmlIdVendas) {
        this.mmlIdVendas = mmlIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mml_idClientes", nullable=false)
    public MmlCliente getMmlCliente() {
        return this.mmlCliente;
    }
    
    public void setMmlCliente(MmlCliente mmlCliente) {
        this.mmlCliente = mmlCliente;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mml_idVendedor", nullable=false)
    public MmlVendedor getMmlVendedor() {
        return this.mmlVendedor;
    }
    
    public void setMmlVendedor(MmlVendedor mmlVendedor) {
        this.mmlVendedor = mmlVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mml_data", length=10)
    public Date getMmlData() {
        return this.mmlData;
    }
    
    public void setMmlData(Date mmlData) {
        this.mmlData = mmlData;
    }

    
    @Column(name="mml_valor", precision=10)
    public double getMmlValor() {
        return this.mmlValor;
    }
    
    public void setMmlValor(double mmlValor) {
        this.mmlValor = mmlValor;
    }

    
    @Column(name="mml_quantidade", length=10)
    public String getMmlQuantidade() {
        return this.mmlQuantidade;
    }
    
    public void setMmlQuantidade(String mmlQuantidade) {
        this.mmlQuantidade = mmlQuantidade;
    }





}


