package bean;
// Generated 21/11/2025 20:16:56 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MmlVendedor generated by hbm2java
 */
@Entity
@Table(name="mml_vendedor"
    ,catalog="db_miguel_leal"
)
public class MmlVendedor  implements java.io.Serializable {


     private int mmlIdVendedor;
     private String mmlNome;
     private int mmlCredencial;
     private String mmlExpediente;
     private String mmlAtivo;
     private String mmlCpf;
     private Date mmlDataNascimente;

    public MmlVendedor() {
    }

    public MmlVendedor(String mmlNome, int mmlCredencial, String mmlExpediente, String mmlAtivo, String mmlCpf, Date mmlDataNascimente) {
       this.mmlNome = mmlNome;
       this.mmlCredencial = mmlCredencial;
       this.mmlExpediente = mmlExpediente;
       this.mmlAtivo = mmlAtivo;
       this.mmlCpf = mmlCpf;
       this.mmlDataNascimente = mmlDataNascimente;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="mml_idVendedor", unique=true, nullable=false)
    public int getMmlIdVendedor() {
        return this.mmlIdVendedor;
    }
    
    public void setMmlIdVendedor(int mmlIdVendedor) {
        this.mmlIdVendedor = mmlIdVendedor;
    }

    
    @Column(name="mml_nome", nullable=false, length=45)
    public String getMmlNome() {
        return this.mmlNome;
    }
    
    public void setMmlNome(String mmlNome) {
        this.mmlNome = mmlNome;
    }

    
    @Column(name="mml_credencial", nullable=false)
    public int getMmlCredencial() {
        return this.mmlCredencial;
    }
    
    public void setMmlCredencial(int mmlCredencial) {
        this.mmlCredencial = mmlCredencial;
    }

    
    @Column(name="mml_expediente", nullable=false, length=1)
    public String getMmlExpediente() {
        return this.mmlExpediente;
    }
    
    public void setMmlExpediente(String mmlExpediente) {
        this.mmlExpediente = mmlExpediente;
    }

    
    @Column(name="mml_ativo", nullable=false, length=1)
    public String getMmlAtivo() {
        return this.mmlAtivo;
    }
    
    public void setMmlAtivo(String mmlAtivo) {
        this.mmlAtivo = mmlAtivo;
    }

    
    @Column(name="mml_cpf", nullable=false, length=14)
    public String getMmlCpf() {
        return this.mmlCpf;
    }
    
    public void setMmlCpf(String mmlCpf) {
        this.mmlCpf = mmlCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mml_data_nascimente", nullable=false, length=10)
    public Date getMmlDataNascimente() {
        return this.mmlDataNascimente;
    }
    
    public void setMmlDataNascimente(Date mmlDataNascimente) {
        this.mmlDataNascimente = mmlDataNascimente;
    }

 @Override
    public String toString(){
        return this.mmlNome;
    }
    
     @Override
        public boolean equals(Object object){
        if (object instanceof MmlVendedor){
            MmlVendedor vendedor = (MmlVendedor)object;
            if (this.getMmlIdVendedor()== vendedor.getMmlIdVendedor()){
                return true;
            }
        }
         return false;
    }
}
