package bean;
// Generated 10/10/2025 16:46:28 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MmlVendasCarros generated by hbm2java
 */
@Entity
@Table(name="mml_vendas_carros"
    ,catalog="db_miguel_leal"
)
public class MmlVendasCarros  implements java.io.Serializable {


     private int mmlIdVendasCarros;
     private MmlCarros mmlCarros;
     private MmlVendas mmlVendas;
     private int mmlQuantidade;
     private double mmlValorUnitario;

    public MmlVendasCarros() {
    }

    public MmlVendasCarros(MmlCarros mmlCarros, MmlVendas mmlVendas, int mmlQuantidade, double mmlValorUnitario) {
       this.mmlCarros = mmlCarros;
       this.mmlVendas = mmlVendas;
       this.mmlQuantidade = mmlQuantidade;
       this.mmlValorUnitario = mmlValorUnitario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="mml_idVendas_carros", unique=true, nullable=false)
    public int getMmlIdVendasCarros() {
        return this.mmlIdVendasCarros;
    }
    
    public void setMmlIdVendasCarros(int mmlIdVendasCarros) {
        this.mmlIdVendasCarros = mmlIdVendasCarros;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mml_idCarros")
    public MmlCarros getMmlCarros() {
        return this.mmlCarros;
    }
    
    public void setMmlCarros(MmlCarros mmlCarros) {
        this.mmlCarros = mmlCarros;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mml_idVenda")
    public MmlVendas getMmlVendas() {
        return this.mmlVendas;
    }
    
    public void setMmlVendas(MmlVendas mmlVendas) {
        this.mmlVendas = mmlVendas;
    }

    
    @Column(name="mml_quantidade")
    public int getMmlQuantidade() {
        return this.mmlQuantidade;
    }
    
    public void setMmlQuantidade(int mmlQuantidade) {
        this.mmlQuantidade = mmlQuantidade;
    }

    
    @Column(name="mml_valor_unitario", precision=10)
    public double getMmlValorUnitario() {
        return this.mmlValorUnitario;
    }
    
    public void setMmlValorUnitario(double mmlValorUnitario) {
        this.mmlValorUnitario = mmlValorUnitario;
    }




}


