/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package MmlView;

import MmlBean.MmlCliente;
import java.awt.Color;
import MmlBean.MmlVendas;
import MmlDao.MmlVendasDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import tools.Util;


/**
 *
 * @author clari
 */
public class MmljDlgVendas extends javax.swing.JDialog {
    Mm_Controller_Vendas_Carros mml_ControllerVendasCarros;
    /**
     * Creates new form MmljDlgVendas
     */
    public MmljDlgVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Cadastro de Vendedor");
        getContentPane().setBackground(Color.WHITE);
        habilitar(false);
        
        
        mml_ControllerVendasCarros = new Mm_Controller_Vendas_Carros();
        mml_ControllerVendasCarros.setList(new ArrayList());
        jTable1.setModel(mml_ControllerVendasCarros);
    
    }

    public void habilitar (boolean value){
      mml_jTxtIdVendas.setEnabled(value);
      mml_jTxtIdClientes.setEnabled(value);
      mml_jTxtValor.setEnabled(value);
      mml_jTxtFormasdePagamento.setEnabled(value);
      mml_FmtDataNasc.setEnabled(value);
      
      
      
      
      mml_jBtnIncluir.setEnabled(!value);
      mml_jBtnAlterar.setEnabled(!value);
      mml_jBtnExcluir.setEnabled(!value);
      mml_jBtnConfirmar.setEnabled(value);
      mml_jBtnCancelar.setEnabled(value);
      mml_jBtnPesquisar.setEnabled(!value);

      
}
    public void limpar() {
    mml_jTxtIdVendas.setText("");
    mml_jTxtIdClientes.setText("");
    mml_jTxtValor.setText("");
    mml_jTxtFormasdePagamento.setText("");
    mml_FmtDataNasc.setText("");
    
}  public void beanView(MmlVendas vendas){
             if (vendas == null) {
            JOptionPane.showMessageDialog(null, "Código não existe");
        } else {
            
         
            mml_jTxtValor.setText(vendas.getMml_jTxtValor());
            mml_jTxtFormasdePagamento.setText(vendas.getMml_jTxtFormasdePagamento());
        }

    }     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cdc_jBtnIncluirProd = new javax.swing.JButton();
        cdc_jBtnAlterarProd = new javax.swing.JButton();
        cdc_jBtnExcluirProd = new javax.swing.JButton();
        mml_jLblFormasdePagamento = new javax.swing.JLabel();
        mml_jBtnExcluir = new javax.swing.JButton();
        mml_jTxtFormasdePagamento = new javax.swing.JTextField();
        mml_jBtnConfirmar = new javax.swing.JButton();
        mml_jBtnCancelar = new javax.swing.JButton();
        mml_jLblData = new javax.swing.JLabel();
        mml_jLblIdVendas = new javax.swing.JLabel();
        mml_jTxtIdVendas = new javax.swing.JTextField();
        mml_jLblIdClientes = new javax.swing.JLabel();
        mml_jTxtIdClientes = new javax.swing.JTextField();
        mml_jBtnPesquisar = new javax.swing.JButton();
        mml_jLblValor = new javax.swing.JLabel();
        mml_jBtnIncluir = new javax.swing.JButton();
        mml_jTxtValor = new javax.swing.JTextField();
        mml_jBtnAlterar = new javax.swing.JButton();
        mml_FmtDataNasc = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cdc_jBtnIncluirProd1 = new javax.swing.JButton();
        cdc_jBtnAlterarProd1 = new javax.swing.JButton();
        cdc_jBtnExcluirProd1 = new javax.swing.JButton();

        cdc_jBtnIncluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        cdc_jBtnIncluirProd.setToolTipText("");
        cdc_jBtnIncluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnIncluirProdActionPerformed(evt);
            }
        });

        cdc_jBtnAlterarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        cdc_jBtnAlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnAlterarProdActionPerformed(evt);
            }
        });

        cdc_jBtnExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        cdc_jBtnExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnExcluirProdActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mml_jLblFormasdePagamento.setText("Forma Pagamento");

        mml_jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        mml_jBtnExcluir.setText("Excluir");
        mml_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnExcluirActionPerformed(evt);
            }
        });

        mml_jTxtFormasdePagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtFormasdePagamentoActionPerformed(evt);
            }
        });

        mml_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        mml_jBtnConfirmar.setText("Confirmar");
        mml_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnConfirmarActionPerformed(evt);
            }
        });

        mml_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        mml_jBtnCancelar.setText("Cancelar");
        mml_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnCancelarActionPerformed(evt);
            }
        });

        mml_jLblData.setText("Data");

        mml_jLblIdVendas.setText("Id Vendas");

        mml_jTxtIdVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtIdVendasActionPerformed(evt);
            }
        });

        mml_jLblIdClientes.setText("Id Cliente");

        mml_jTxtIdClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtIdClientesActionPerformed(evt);
            }
        });

        mml_jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar (2)_1.png"))); // NOI18N
        mml_jBtnPesquisar.setText("Pesquisar");
        mml_jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnPesquisarActionPerformed(evt);
            }
        });

        mml_jLblValor.setText("Valor");

        mml_jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        mml_jBtnIncluir.setText("Incluir");
        mml_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnIncluirActionPerformed(evt);
            }
        });

        mml_jTxtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtValorActionPerformed(evt);
            }
        });

        mml_jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        mml_jBtnAlterar.setText("Alterar");
        mml_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnAlterarActionPerformed(evt);
            }
        });

        mml_FmtDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_FmtDataNascActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        cdc_jBtnIncluirProd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        cdc_jBtnIncluirProd1.setToolTipText("");
        cdc_jBtnIncluirProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnIncluirProd1ActionPerformed(evt);
            }
        });

        cdc_jBtnAlterarProd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        cdc_jBtnAlterarProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnAlterarProd1ActionPerformed(evt);
            }
        });

        cdc_jBtnExcluirProd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        cdc_jBtnExcluirProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnExcluirProd1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(mml_jTxtFormasdePagamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(mml_jTxtIdVendas, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mml_jLblIdVendas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mml_jLblFormasdePagamento))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mml_jTxtIdClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mml_jLblIdClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mml_jLblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mml_jTxtValor)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mml_jLblData, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mml_FmtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jBtnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jBtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jBtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jBtnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jBtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jBtnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cdc_jBtnAlterarProd1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(cdc_jBtnIncluirProd1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cdc_jBtnExcluirProd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblIdClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtIdClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblIdVendas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtIdVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblFormasdePagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mml_jTxtFormasdePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mml_FmtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblData)
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mml_jBtnIncluir)
                            .addComponent(mml_jBtnAlterar)
                            .addComponent(mml_jBtnExcluir)
                            .addComponent(mml_jBtnConfirmar)
                            .addComponent(mml_jBtnCancelar)
                            .addComponent(mml_jBtnPesquisar))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cdc_jBtnIncluirProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jBtnAlterarProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jBtnExcluirProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mml_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "Confirma Exclusão ?");
        if (resp == JOptionPane.YES_NO_OPTION) {
            MmlVendas venda = new MmlVendas();
            int codigo = Integer.parseInt(mml_jTxtIdVendas.getText());
            venda.setMml_jTxtIdVendas(codigo);
            venda.setMml_jTxtIdClientes(mml_jTxtIdClientes.getText());
            venda.setMml_jTxtValor(mml_jTxtValor.getText());
            venda.setMml_jTxtFormasdePagamento(mml_jTxtFormasdePagamento.getText());
            venda.setMml_jFmtData(null); // ou use um parser se for preencher com valor da tela

            MmlVendasDao vendasDao = new MmlVendasDao();
            vendasDao.delete(venda);
}
limpar();

    }//GEN-LAST:event_mml_jBtnExcluirActionPerformed

    private void mml_jTxtFormasdePagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtFormasdePagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtFormasdePagamentoActionPerformed

    private void mml_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        MmlVendas venda = new MmlVendas();
        int codigo = Integer.parseInt(mml_jTxtIdVendas.getText());
        venda.setMml_jTxtIdVendas(codigo);
        venda.setMml_jTxtIdClientes(mml_jTxtIdClientes.getText());
        venda.setMml_jTxtValor(mml_jTxtValor.getText());
        venda.setMml_jTxtFormasdePagamento(mml_jTxtFormasdePagamento.getText());
        venda.setMml_jFmtData(null); 

        MmlVendasDao vendasDao = new MmlVendasDao();
        vendasDao.insert(venda);
        habilitar(false);

    }//GEN-LAST:event_mml_jBtnConfirmarActionPerformed

    private void mml_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
        JOptionPane.showConfirmDialog(null, "Você deseja cancelar?");
        limpar();
    }//GEN-LAST:event_mml_jBtnCancelarActionPerformed

    private void mml_jTxtIdVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtIdVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtIdVendasActionPerformed

    private void mml_jTxtIdClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtIdClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtIdClientesActionPerformed

    private void mml_jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        String id = JOptionPane.showInputDialog(null, "Entre com o código ?");
        int codigo = Integer.valueOf(id);
        MmlVendasDao vendasDao = new MmlVendasDao();
        MmlVendas venda = (MmlVendas) vendasDao.list(codigo);
        if (venda == null) {
            JOptionPane.showMessageDialog(null, "Código não existe");
        } else {
            mml_jTxtIdVendas.setText(id);
            mml_jTxtIdClientes.setText(venda.getMml_jTxtIdClientes());
            mml_jTxtValor.setText(venda.getMml_jTxtValor());
            mml_jTxtFormasdePagamento.setText(venda.getMml_jTxtFormasdePagamento());
        }

    }//GEN-LAST:event_mml_jBtnPesquisarActionPerformed

    private void mml_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        limpar();
    }//GEN-LAST:event_mml_jBtnIncluirActionPerformed

    private void mml_jTxtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtValorActionPerformed

    private void mml_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        habilitar(true);
    }//GEN-LAST:event_mml_jBtnAlterarActionPerformed

    private void mml_FmtDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_FmtDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_FmtDataNascActionPerformed

    private void cdc_jBtnIncluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnIncluirProdActionPerformed
        // TODO add your handling code here:
        MmljDlgVendasCarros jDlgVendasProdutos = new MmljDlgVendasCarros(null, true);
        jDlgVendasProdutos.setTelaAnterior(this);
        jDlgVendasProdutos.setVisible(true);
        

    }//GEN-LAST:event_cdc_jBtnIncluirProdActionPerformed

    private void cdc_jBtnAlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnAlterarProdActionPerformed
        // TODO add your handling code here:
        MmljDlgVendasCarros jDlgVendasProdutos = new MmljDlgVendasCarros(null, true);
        jDlgVendasProdutos.setVisible(true);
    }//GEN-LAST:event_cdc_jBtnAlterarProdActionPerformed

    private void cdc_jBtnExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnExcluirProdActionPerformed
        // TODO add your handling code here:

        int rowIndex = jTable1.getSelectedRow();
        if (rowIndex == -1) {
            Util.mensagem("Selecione uma linhaaa primeiro");
            return;
        }
        if (Util.perguntar("Deseja realmete Excluir?") == true) {
            mml_ControllerVendasCarros.removeBean(rowIndex);
            
        }
    }//GEN-LAST:event_cdc_jBtnExcluirProdActionPerformed

    private void cdc_jBtnIncluirProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnIncluirProd1ActionPerformed
        // TODO add your handling code here:
        MmljDlgVendasCarros jDlgVendasProdutos = new MmljDlgVendasCarros(null, true);
        jDlgVendasProdutos.setTelaAnterior(this);
        jDlgVendasProdutos.setVisible(true);
       

    }//GEN-LAST:event_cdc_jBtnIncluirProd1ActionPerformed

    private void cdc_jBtnAlterarProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnAlterarProd1ActionPerformed
        // TODO add your handling code here:
        MmljDlgVendasCarros jDlgVendasProdutos = new MmljDlgVendasCarros(null, true);
        jDlgVendasProdutos.setVisible(true);
    }//GEN-LAST:event_cdc_jBtnAlterarProd1ActionPerformed

    private void cdc_jBtnExcluirProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnExcluirProd1ActionPerformed
        // TODO add your handling code here:

        int rowIndex = jTable1.getSelectedRow();
        if (rowIndex == -1) {
            Util.mensagem("Selecione alguma linha primeiro");
            return;
        }
        if (Util.perguntar("Deseja Excluir?") == true) {
            mml_ControllerVendasCarros.removeBean(rowIndex);
           
        }
    }//GEN-LAST:event_cdc_jBtnExcluirProd1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MmljDlgVendas dialog = new MmljDlgVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cdc_jBtnAlterarProd;
    private javax.swing.JButton cdc_jBtnAlterarProd1;
    private javax.swing.JButton cdc_jBtnExcluirProd;
    private javax.swing.JButton cdc_jBtnExcluirProd1;
    private javax.swing.JButton cdc_jBtnIncluirProd;
    private javax.swing.JButton cdc_jBtnIncluirProd1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JFormattedTextField mml_FmtDataNasc;
    private javax.swing.JButton mml_jBtnAlterar;
    private javax.swing.JButton mml_jBtnCancelar;
    private javax.swing.JButton mml_jBtnConfirmar;
    private javax.swing.JButton mml_jBtnExcluir;
    private javax.swing.JButton mml_jBtnIncluir;
    private javax.swing.JButton mml_jBtnPesquisar;
    private javax.swing.JLabel mml_jLblData;
    private javax.swing.JLabel mml_jLblFormasdePagamento;
    private javax.swing.JLabel mml_jLblIdClientes;
    private javax.swing.JLabel mml_jLblIdVendas;
    private javax.swing.JLabel mml_jLblValor;
    private javax.swing.JTextField mml_jTxtFormasdePagamento;
    private javax.swing.JTextField mml_jTxtIdClientes;
    private javax.swing.JTextField mml_jTxtIdVendas;
    private javax.swing.JTextField mml_jTxtValor;
    // End of variables declaration//GEN-END:variables
}
