/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package MmlView;

import MmlBean.MmlUsuarios;
import MmlBean.MmlVendedor;
import MmlDao.MmlVendedorDao;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author clari
 */
public class MmljDlgVendedor extends javax.swing.JDialog {
    boolean incluir = false;
    private MaskFormatter mascaraCpf, mascaraDataNasc;

    /**
     * Creates new form jDlgVendedor
     */
    public MmljDlgVendedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
               initComponents();

        setLocationRelativeTo(null);
        setTitle("Cadastro de Vendedor");
        getContentPane().setBackground(Color.WHITE);
        habilitar(false);
        try {
            mascaraCpf = new MaskFormatter("###.###.###-##");
            mascaraDataNasc = new MaskFormatter("##/##/####");
            mml_jFmtCpf.setFormatterFactory(new DefaultFormatterFactory(mascaraCpf));
            mml_jFmtDataNasc.setFormatterFactory(new DefaultFormatterFactory(mascaraDataNasc));

        } catch (ParseException ex) {
            Logger.getLogger(MmljDlgCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void habilitar(boolean value) {
        mml_jTxtCodigoo.setEnabled(value);
        mml_jTxtNome.setEnabled(value);
        mml_jFmtCpf.setEnabled(value);
        mml_jTxtCredencial.setEnabled(value);
        mml_jFmtDataNasc.setEnabled(value);
        mml_jTxtExpediente.setEnabled(value);
        mml_jCBocAtivo.setEnabled(value);

        mml_jBtnIncluir.setEnabled(!value);
        mml_jBtnAlterar.setEnabled(!value);
        mml_jBtnExcluir.setEnabled(!value);
        mml_jBtnConfirmar.setEnabled(value);
        mml_jBtnCancelar.setEnabled(value);
        mml_jBtnPesquisar.setEnabled(!value);

    }

    public void limpar() {
        mml_jTxtCodigoo.setText("");
        mml_jTxtNome.setText("");
        mml_jTxtCredencial.setText("");
        mml_jTxtExpediente.setText("");
        mml_jFmtDataNasc.setText("");
        mml_jFmtCpf.setText("");
        mml_jCBocAtivo.setSelected(false);
    }

    public void beanView(MmlVendedor vendedor) {
      
            vendedor.setNome(mml_jTxtNome.getText());
            vendedor.setCredencial(mml_jTxtCredencial.getText());
            vendedor.setExpediente(mml_jTxtExpediente.getText());
            vendedor.setCpf(mml_jFmtCpf.getText());
            vendedor.setDatanascimento(null);
            if (mml_jCBocAtivo.isSelected() == true) {
                vendedor.setAtivo("S");
            } else {
                vendedor.setAtivo("N");
            }
    }
        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mml_jLblNome = new javax.swing.JLabel();
        mml_jTxtNome = new javax.swing.JTextField();
        mml_jLblCodigo = new javax.swing.JLabel();
        mml_jTxtCodigoo = new javax.swing.JTextField();
        mml_jLblCredencial = new javax.swing.JLabel();
        mml_jTxtCredencial = new javax.swing.JTextField();
        mml_jLblExpediente = new javax.swing.JLabel();
        mml_jTxtExpediente = new javax.swing.JTextField();
        mml_jLblCpf = new javax.swing.JLabel();
        mml_jLblDataNasc = new javax.swing.JLabel();
        mml_jLblAtivo = new javax.swing.JLabel();
        mml_jCBocAtivo = new javax.swing.JCheckBox();
        mml_jBtnPesquisar = new javax.swing.JButton();
        mml_jBtnIncluir = new javax.swing.JButton();
        mml_jBtnAlterar = new javax.swing.JButton();
        mml_jBtnExcluir = new javax.swing.JButton();
        mml_jBtnConfirmar = new javax.swing.JButton();
        mml_jBtnCancelar = new javax.swing.JButton();
        mml_jFmtCpf = new javax.swing.JFormattedTextField();
        mml_jFmtDataNasc = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mml_jLblNome.setText("Nome");

        mml_jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtNomeActionPerformed(evt);
            }
        });

        mml_jLblCodigo.setText("Código");

        mml_jTxtCodigoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtCodigooActionPerformed(evt);
            }
        });

        mml_jLblCredencial.setText("Credencial");

        mml_jTxtCredencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtCredencialActionPerformed(evt);
            }
        });

        mml_jLblExpediente.setText("Expediente");

        mml_jTxtExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtExpedienteActionPerformed(evt);
            }
        });

        mml_jLblCpf.setText("CPF");

        mml_jLblDataNasc.setText("Data de Nascimento");

        mml_jLblAtivo.setText("Ativo");

        mml_jCBocAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jCBocAtivoActionPerformed(evt);
            }
        });

        mml_jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar (2)_1.png"))); // NOI18N
        mml_jBtnPesquisar.setText("Pesquisar");
        mml_jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnPesquisarActionPerformed(evt);
            }
        });

        mml_jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        mml_jBtnIncluir.setText("Incluir");
        mml_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnIncluirActionPerformed(evt);
            }
        });

        mml_jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        mml_jBtnAlterar.setText("Alterar");
        mml_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnAlterarActionPerformed(evt);
            }
        });

        mml_jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        mml_jBtnExcluir.setText("Excluir");
        mml_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnExcluirActionPerformed(evt);
            }
        });

        mml_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        mml_jBtnConfirmar.setText("Confirmar");
        mml_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnConfirmarActionPerformed(evt);
            }
        });

        mml_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        mml_jBtnCancelar.setText("Cancelar");
        mml_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(mml_jTxtExpediente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(mml_jLblNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mml_jTxtNome, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(mml_jLblExpediente))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mml_jTxtCodigoo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mml_jLblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mml_jLblCredencial, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mml_jTxtCredencial)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mml_jLblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mml_jFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(mml_jLblAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mml_jFmtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(mml_jCBocAtivo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mml_jBtnIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mml_jBtnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mml_jBtnExcluir)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(mml_jBtnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jBtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jBtnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblCredencial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtCredencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtCodigoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblExpediente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mml_jTxtExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mml_jFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblCpf)
                        .addGap(28, 28, 28)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mml_jLblDataNasc)
                    .addComponent(mml_jLblAtivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mml_jCBocAtivo)
                    .addComponent(mml_jFmtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mml_jBtnIncluir)
                    .addComponent(mml_jBtnAlterar)
                    .addComponent(mml_jBtnExcluir)
                    .addComponent(mml_jBtnConfirmar)
                    .addComponent(mml_jBtnCancelar)
                    .addComponent(mml_jBtnPesquisar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mml_jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtNomeActionPerformed

    private void mml_jTxtCodigooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtCodigooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtCodigooActionPerformed

    private void mml_jTxtCredencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtCredencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtCredencialActionPerformed

    private void mml_jTxtExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtExpedienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtExpedienteActionPerformed

    private void mml_jCBocAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jCBocAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jCBocAtivoActionPerformed

    private void mml_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "Confirma Exclusão ?");
        if (resp == JOptionPane.YES_NO_OPTION) {
            MmlVendedor vendedor = new MmlVendedor();
            int codigo = Integer.parseInt(mml_jTxtCodigoo.getText());
            vendedor.setIdVendedor(codigo);
            vendedor.setNome(mml_jTxtNome.getText());
            vendedor.setCredencial(mml_jTxtCredencial.getText());
            vendedor.setExpediente(mml_jTxtExpediente.getText());
            vendedor.setCpf(mml_jFmtCpf.getText());
            vendedor.setDatanascimento(null);
            if (mml_jCBocAtivo.isSelected() == true) {
                vendedor.setAtivo("S");
            } else {
                vendedor.setAtivo("N");
            }
            MmlVendedorDao vendedorDao = new MmlVendedorDao();
            vendedorDao.delete(vendedor);
        }
        limpar();

    }//GEN-LAST:event_mml_jBtnExcluirActionPerformed

    private void mml_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        limpar();
    }//GEN-LAST:event_mml_jBtnIncluirActionPerformed

    private void mml_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        MmlVendedor vendedor = new MmlVendedor();
        int codigo = Integer.parseInt(mml_jTxtCodigoo.getText());
        vendedor.setIdVendedor(codigo);
        vendedor.setNome(mml_jTxtNome.getText());
        vendedor.setCredencial(mml_jTxtCredencial.getText());
        vendedor.setExpediente(mml_jTxtExpediente.getText());
        vendedor.setCpf(mml_jFmtCpf.getText());
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Date dataNasc = formato.parse(mml_jFmtDataNasc.getText());
        vendedor.setDatanascimento(dataNasc);
        
        
        } catch (ParseException ex) {
            Logger.getLogger(MmljDlgCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (mml_jCBocAtivo.isSelected() == true) {
            vendedor.setAtivo("S");
        } else {
            vendedor.setAtivo("N");
        }
        MmlVendedorDao vendedorDao = new MmlVendedorDao();
        vendedorDao.insert(vendedor);
        habilitar(false);
    }//GEN-LAST:event_mml_jBtnConfirmarActionPerformed

    private void mml_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
        JOptionPane.showConfirmDialog(null, "Você deseja cancelar?");
        limpar();
    }//GEN-LAST:event_mml_jBtnCancelarActionPerformed

    private void mml_jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
//        String id = JOptionPane.showInputDialog(null, "Entre com o código ?");
//        int codigo = Integer.valueOf(id);
//        MmlVendedorDao vendedorDao = new MmlVendedorDao();
//        MmlVendedor vendedor = (MmlVendedor) vendedorDao.list(codigo);
//        if (vendedor == null) {
//            JOptionPane.showMessageDialog(null, "Código não existe");
//        } else {
//            mml_jTxtCodigoo.setText(id);
//            mml_jTxtNome.setText(vendedor.getNome());
//            mml_jTxtCredencial.setText(vendedor.getCredencial());
//            mml_jTxtExpediente.setText(vendedor.getExpediente());
//            mml_jTxtCpf.setText(vendedor.getCpf());
//            // jTxtDataNascimento.setText(""); // opcional, se tiver esse campo
//            if (vendedor.getAtivo().equals("S")) {
//                mml_jCBocAtivo.setSelected(true);
//            } else {
//                mml_jCBocAtivo.setSelected(false);
//            }
//        }
        Mml_jDlgVendedorPesquisar jdDlgVendedorPesquisar = new Mml_jDlgVendedorPesquisar(null, true);
        jdDlgVendedorPesquisar.setTelaPai(this);
        jdDlgVendedorPesquisar.setVisible(true);

    }//GEN-LAST:event_mml_jBtnPesquisarActionPerformed

    private void mml_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        incluir = false;
        mml_jTxtNome.grabFocus();
    }//GEN-LAST:event_mml_jBtnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MmljDlgVendedor dialog = new MmljDlgVendedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mml_jBtnAlterar;
    private javax.swing.JButton mml_jBtnCancelar;
    private javax.swing.JButton mml_jBtnConfirmar;
    private javax.swing.JButton mml_jBtnExcluir;
    private javax.swing.JButton mml_jBtnIncluir;
    private javax.swing.JButton mml_jBtnPesquisar;
    private javax.swing.JCheckBox mml_jCBocAtivo;
    private javax.swing.JFormattedTextField mml_jFmtCpf;
    private javax.swing.JFormattedTextField mml_jFmtDataNasc;
    private javax.swing.JLabel mml_jLblAtivo;
    private javax.swing.JLabel mml_jLblCodigo;
    private javax.swing.JLabel mml_jLblCpf;
    private javax.swing.JLabel mml_jLblCredencial;
    private javax.swing.JLabel mml_jLblDataNasc;
    private javax.swing.JLabel mml_jLblExpediente;
    private javax.swing.JLabel mml_jLblNome;
    private javax.swing.JTextField mml_jTxtCodigoo;
    private javax.swing.JTextField mml_jTxtCredencial;
    private javax.swing.JTextField mml_jTxtExpediente;
    private javax.swing.JTextField mml_jTxtNome;
    // End of variables declaration//GEN-END:variables
}
