/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package MmlView;
import MmlBean.MmlVendasCarros;
import MmlDao.MmlVendasCarrosDao;
import java.awt.Color;
import javax.swing.JOptionPane;
import tools.Util;

/**
 *
 * @author clari
 */
public class MmljDlgVendasCarros extends javax.swing.JDialog {
    MmljDlgVendas mmlJDlgVendas;
    /**
     * Creates new form MmljDlgVendasProdutos
     */
    public MmljDlgVendasCarros(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Cadastro de Vendas de Carros");
        getContentPane().setBackground(Color.WHITE);
        habilitar(false);
    }
    
        public void habilitar(boolean value) {
        mml_jTxtIdVendasCarros.setEnabled(value);
        mml_jTxtIdVendas.setEnabled(value);
        mml_jTxtIdCarros.setEnabled(value);
        mml_jTxtQuantidade.setEnabled(value);
        mml_jTxtValorUnitario.setEnabled(value);

       
    }
        public void limpar() {
        mml_jTxtIdVendasCarros.setText("");
        mml_jTxtIdVendas.setText("");
        mml_jTxtIdCarros.setText("");
        mml_jTxtQuantidade.setText("");
        mml_jTxtValorUnitario.setText("");
}
        public void setTelaAnterior(MmljDlgVendas mmlJDlgVendas){
        this.mmlJDlgVendas = mmlJDlgVendas;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mml_jTxtIdCarros = new javax.swing.JTextField();
        mml_jBtnCancelar = new javax.swing.JButton();
        mml_jLblValorUnitario = new javax.swing.JLabel();
        mml_jLblIdVendasCarros = new javax.swing.JLabel();
        mml_jTxtValorUnitario = new javax.swing.JTextField();
        mml_jTxtIdVendasCarros = new javax.swing.JTextField();
        mml_jLblIdVenda = new javax.swing.JLabel();
        mml_jTxtIdVendas = new javax.swing.JTextField();
        mml_jLblTipo = new javax.swing.JLabel();
        mml_jLblIdCarros = new javax.swing.JLabel();
        mml_jTxtQuantidade = new javax.swing.JTextField();
        mml_jBtnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mml_jTxtIdCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtIdCarrosActionPerformed(evt);
            }
        });

        mml_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        mml_jBtnCancelar.setText("Cancelar");
        mml_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnCancelarActionPerformed(evt);
            }
        });

        mml_jLblValorUnitario.setText("Valor Unitario");

        mml_jLblIdVendasCarros.setText("Id Vendas_Carros");

        mml_jTxtValorUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtValorUnitarioActionPerformed(evt);
            }
        });

        mml_jTxtIdVendasCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtIdVendasCarrosActionPerformed(evt);
            }
        });

        mml_jLblIdVenda.setText("Id Venda");

        mml_jTxtIdVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtIdVendasActionPerformed(evt);
            }
        });

        mml_jLblTipo.setText("Quantidade");

        mml_jLblIdCarros.setText("Id Carros");

        mml_jTxtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jTxtQuantidadeActionPerformed(evt);
            }
        });

        mml_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        mml_jBtnConfirmar.setText("Confirmar");
        mml_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mml_jBtnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(mml_jTxtQuantidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(mml_jTxtIdVendasCarros, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mml_jLblIdVendasCarros, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(mml_jLblTipo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mml_jTxtIdVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mml_jLblIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mml_jLblIdCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mml_jTxtIdCarros, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mml_jLblValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mml_jTxtValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jBtnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jBtnCancelar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblIdCarros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtIdCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblIdVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtIdVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblIdVendasCarros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtIdVendasCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mml_jLblValorUnitario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mml_jTxtValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mml_jBtnConfirmar)
                    .addComponent(mml_jBtnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mml_jTxtIdCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtIdCarrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtIdCarrosActionPerformed

    private void mml_jTxtValorUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtValorUnitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtValorUnitarioActionPerformed

    private void mml_jTxtIdVendasCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtIdVendasCarrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtIdVendasCarrosActionPerformed

    private void mml_jTxtIdVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtIdVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtIdVendasActionPerformed

    private void mml_jTxtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jTxtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mml_jTxtQuantidadeActionPerformed

    private void mml_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        MmlVendasCarros vendaCarro = new MmlVendasCarros();
        int codigo = Integer.parseInt(mml_jTxtIdVendasCarros.getText());
        vendaCarro.setIdVendasCarros(codigo);
        vendaCarro.setIdVenda(mml_jTxtIdVendas.getText());
        vendaCarro.setIdCarros(mml_jTxtIdCarros.getText());
        vendaCarro.setQuantidade(Util.strToInt(mml_jTxtQuantidade.getText()));
        vendaCarro.setValorUnitario(Util.strToDouble(mml_jTxtValorUnitario.getText()));

        MmlVendasCarrosDao vendasCarrosDao = new MmlVendasCarrosDao();
        vendasCarrosDao.insert(vendaCarro);
        habilitar(false);

    }//GEN-LAST:event_mml_jBtnConfirmarActionPerformed

    private void mml_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mml_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
        JOptionPane.showConfirmDialog(null, "Você deseja cancelar?");
        limpar();
    }//GEN-LAST:event_mml_jBtnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendasCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendasCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendasCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MmljDlgVendasCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MmljDlgVendasCarros dialog = new MmljDlgVendasCarros(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mml_jBtnCancelar;
    private javax.swing.JButton mml_jBtnConfirmar;
    private javax.swing.JLabel mml_jLblIdCarros;
    private javax.swing.JLabel mml_jLblIdVenda;
    private javax.swing.JLabel mml_jLblIdVendasCarros;
    private javax.swing.JLabel mml_jLblTipo;
    private javax.swing.JLabel mml_jLblValorUnitario;
    private javax.swing.JTextField mml_jTxtIdCarros;
    private javax.swing.JTextField mml_jTxtIdVendas;
    private javax.swing.JTextField mml_jTxtIdVendasCarros;
    private javax.swing.JTextField mml_jTxtQuantidade;
    private javax.swing.JTextField mml_jTxtValorUnitario;
    // End of variables declaration//GEN-END:variables
}
